#########################################################################################
######################### AWICM 1 YAML CONFIGURATION FILE ###############################
#########################################################################################

general:
        model: awicmcr
        #model_dir: ${esm_master_dir}/awicmcr-${version}

        coupled_setup: True

        include_models:
                - echam
                - fesom
                - oasis3mct

        version: "1.1"
        available_versions:
        - '1.0'
        - CMIP6
        - '2.0'
        choose_version:
          '1.0':
            couplings:
            - fesom-1.4+echam-6.3.05p2-concurrent_radiation
          '2.0':
            couplings:
            - fesom-2.0+echam-6.3.05p2-concurrent_radiation
          CMIP6:
            couplings:
            - fesom-1.4+echam-6.3.05p2-concurrent_radiation
        scenario: "PI-CTRL"
        resolution: ${echam.resolution}_${fesom.resolution}
        postprocessing: false
        post_time: "00:05:00"
        choose_general.resolution:
                T63_CORE2:
                        compute_time: "02:00:00"
                T63_REF87K:
                        compute_time: "02:00:00"
                T63_REF:
                        compute_time: "02:00:00"


#########################################################################################
########### necessary changes to submodels compared to standalone setups ################
#########################################################################################

echam:
        restart_firstlast: "first"
        namelist_changes:
                namelist.echam:
                        runctl:
                                lcouple: .true.
        adj_input_dir: "${fesom.mesh_dir}/tarfiles${echam.resolution}/input/echam6"
        model_dir: ${general.model_dir}/echam-${echam.version}
        setup_dir: ${general.model_dir}
        ocean_resolution: "${fesom.resolution}"

        remove_forcing_files:
                - sst
                - sic
        version: "6.3.05p2-concurrent_radiation"

# kh 20.03.20 parameter values below may be superseded by section choose_computer.cores_per_node: ... nproca ...,
# or by section choose_version: ... nproca ..., ... in esm_tools/configs/echam/echam.yaml
        choose_general.resolution:
                T63_CORE2:
                        nproca: 24
                        nprocb: 18

# kh 30.04.20 nprocrad is replaced by more flexible partitioning using nprocar and nprocbr
#                       nprocrad: 432
                        nprocar: 48
                        nprocbr: 36

                        npromar: 16
                        lrad_async: true
                        lrestart_from_old: false

                T63_REF87K:
                        nproca: 24
                        nprocb: 18

# kh 30.04.20 nprocrad is replaced by more flexible partitioning using nprocar and nprocbr
#                       nprocrad: 432
                        nprocar: 24
                        nprocbr: 18

                        npromar: 8
                        lrad_async: true
                        lrestart_from_old: false

                T63_REF:
                        nproca: 24
                        nprocb: 18

# kh 30.04.20 nprocrad is replaced by more flexible partitioning using nprocar and nprocbr
#                       nprocrad: 432
                        nprocar: 24
                        nprocbr: 18

                        npromar: 8
                        lrad_async: true
                        lrestart_from_old: false


#########################################################################################


jsbach:
        adj_input_dir: "${fesom.mesh_dir}/tarfiles${echam.resolution}/input/jsbach"
        namelist_changes:
                namelist.jsbach:
                        hydrology_ctl:
                                gethd: "remove_from_namelist"
                                puthd: "remove_from_namelist"
        version: "3.20"

        choose_computer.name:
                ollie:
                        dynveg_file_ending: ""
                        no_dynveg_file_ending: ""

#########################################################################################


fesom:
        choose_general.version:
                "1.1":
                        version: "1.4"
                "CMIP6":
                        version: "1.4"
                "2.0":
                        version: "2.0"
        choose_general.resolution:
                T63_CORE2:
                        nproc: 288
                T63_REF87K:
                        nproc: 216
                T63_REF:
                        nproc: 128

        opbnd_dir: ""
        tide_forcing_dir: ""
        forcing_data_dir: ""
        model_dir: ${general.model_dir}/fesom-${fesom.version}
        setup_dir: ${general.model_dir}

        add_namelist_changes:
                namelist.oce:
                        boundary:
                                restore_s_surf: 0.0

        leapyear: True
        asforcing: ECHAM5






#########################################################################################

oasis3mct:
        model_dir: ${general.model_dir}/oasis

        process_ordering:
                - fesom
                - echam

        a2o_lag: "${echam.time_step}"
        o2a_lag: "${fesom.time_step}"
        a2o_seq: 2

        coupling_time_step: 3600
        coupling_target_fields:
                o2a_flux:
                        - 'sst_atmo:sit_atmo:sie_atmo <--distwgt-- sst_feom:sit_feom:sie_feom'
                        - 'snt_atmo <--distwgt-- snt_feom'

                a2o_flux:
                        - 'taux_oce:tauy_oce:taux_ico:tauy_ico <--bicubic-- taux_atm:tauy_atm:taux_ica:tauy_ica'
                        - 'prec_oce <--distwgt-- prec_atm'
                        - 'snow_oce <--distwgt-- snow_atm'
                        - 'evap_oce <--distwgt-- evap_atm'
                        - 'subl_oce <--distwgt-- subl_atm'
                        - 'heat_oce <--distwgt-- heat_atm'
                        - 'heat_ico <--distwgt-- heat_ica'
                        - 'heat_swo <--distwgt-- heat_swa'
                        - 'hydr_oce <--distwgt-- hydr_atm'


        coupling_directions:
                'feom->atmo':
                        lag: ${o2a_lag}
                        seq: 2
                'atmo->feom':
                        lag: ${a2o_lag}
                        seq: ${a2o_seq}


        coupling_methods:
                distwgt:
                        time_transformation: instant
                        remapping:
                                distwgt:
                                        search_bin: latitude
                                        nb_of_search_bins: 15
                                        nb_of_neighbours: 6
                bicubic:
                        time_transformation: instant
                        remapping:
                                bicubic:
                                        search_bin: latitude
                                        nb_of_search_bins: 15

        add_restart_out_files:
                rmp_a2f_B: rmp_a2f_B
                rmp_a2f_D: rmp_a2f_D
                rmp_f2a_D: rmp_f2a_D

        add_restart_out_in_work:
                rmp_a2f_B: rmp_atmo_to_feom_BICUBIC.nc
                rmp_a2f_D: rmp_atmo_to_feom_DISTWGT.nc
                rmp_f2a_D: rmp_feom_to_atmo_DISTWGT.nc

        add_restart_out_sources:
                rmp_a2f_B: rmp_atmo_to_feom_BICUBIC.nc
                rmp_a2f_D: rmp_atmo_to_feom_DISTWGT.nc
                rmp_f2a_D: rmp_feom_to_atmo_DISTWGT.nc

        add_restart_in_files:
                rmp_a2f_B: rmp_a2f_B
                rmp_a2f_D: rmp_a2f_D
                rmp_f2a_D: rmp_f2a_D

        add_restart_in_in_work:
                rmp_a2f_B: rmp_atmo_to_feom_BICUBIC.nc
                rmp_a2f_D: rmp_atmo_to_feom_DISTWGT.nc
                rmp_f2a_D: rmp_feom_to_atmo_DISTWGT.nc

        add_restart_in_sources:
                rmp_a2f_B: rmp_atmo_to_feom_BICUBIC.nc
                rmp_a2f_D: rmp_atmo_to_feom_DISTWGT.nc
                rmp_f2a_D: rmp_feom_to_atmo_DISTWGT.nc


