computer:
        choose_computer.name:
                levante:
                        add_module_actions:
                                - "load perl"
        choose_general.execution_mode:
                run:
                        add_export_vars:
                                OMPI_MCA_osc: "ucx"
