#########################################################################################
########################### AMIP YAML CONFIGURATION FILE  ###############################
#########################################################################################
general:

        model: oifsamip

        model_dir: ${esm_master_dir}/oifsamip

        lresume: False
        coupled_setup: True

        include_models:
                - amip
                - oifs
                - oasis3mct

        available_versions:
                - 'cy43'
        choose_version:
          cy43:
            couplings:
              - oifs-43r3-awicm-3.0+amip-v1

        version: "cy43"
        scenario: "piControl"
        resolution: ${oifs.resolution}
        postprocessing: false
        post_time: "00:05:00"
        compute_time: "00:30:00"

        reusable_filetypes: [input, bin, src]

        choose_computer.name:
                mistral:
                        pool_dir: "/work/ab0246/a270092/input"
                ollie:
                        pool_dir: "/work/ollie/jstreffi/input"
                juwels:
                        pool_dir: "/p/project/chhb19/jstreffi/input"
                aleph:
                        pool_dir: "/proj/awi/input"

        # Load compute recipe from oifs.yaml
        compute_recipe: ${oifs.compute_recipe}

        # Load general environment for the whole coupled setup
        dr_hook_ignore_signals: -1
        further_reading:
                - oifs/oifs43.env.yaml
                - oasis3mct/oasis3mct.env.yaml


#########################################################################################
########### necessary changes to submodels compared to standalone setups ################
#########################################################################################

oifs:
        version: "43r3"

        add_compute_recipe: ["oasis_rmp_rst_to_input"]
        execution_command: ${executable} -v ecmwf -e ${oifs.input_expid}

        pool_dir: ${general.pool_dir}
        model_dir: ${general.model_dir}/oifs-${version}
        setup_dir: ${general.model_dir}
        restart_firstlast: "last"
        restart_rate: 12

        mip: "cmip6"
        scenario: "historical"

        prepifs_expid: h6mv
        input_expid: awi3   # This cannot be longer than 4 characters
        input_dir: ${pool_dir}/oifs-${version}
        rtables_dir: ${input_dir}/rtables/
        forcing_dir: ${input_dir}/${version}/ifsdata/
        ifsdata_dir: ${input_dir}/${version}/ifsdata/
        choose_general.version:
                "cy43":
                        namelist_dir: ${general.esm_namelist_dir}/oifs/${version}/awicm3/v3.0

        add_namelist_changes:
                fort.4:
                        NAMECECFG:
                                ECE_CPL_NEMO_LIM: ".false."
                                ECE_CPL_FESOM_FESIM: ".false."
                        NAMAWICFG:
                                ECE_AWI_CPL_FESOM: ".false."

        cmip6_data_dir_nml: ${input_dir}/cmip6-data
        cmip5_data_dir_nml: ${input_dir}/cmip5-data

        # nproc must be not a prime number for OpenIFS parallelisation to work
        # (This is just one of the many mysteries of the IFS...)
        #
        # We want to use 1 CPU for runoff mapper
        # 287 fulfills this requirement and 288 divides well with 36 and 48
        # (287 = 41 * 7)
        # so that the configuration fills up the compute nodes
        # 575 would also be ok (575 = 23 * 25)
        # Note: If we don't use MPI/OMP we don't need full nodes for oifs.
        nproc: 36
        omp_num_threads: 2
        choose_general.resolution:
                TL159_CORE2:
                        nproc: 36
                TCO159_CORE2:
                        nproc: 36

        # Wave model switch
        wam: true

        perturb: 0
        ensemble_id: 1

        # Microphysics switch: 0 for off, 1 for light version and 2 for full
        sclct_switch: 2

        resolution: TCO159
        levels: L91


        runtime_environment_changes:
                add_export_vars:
                        # Turn on AMIP coupling through the FESOM interface in OpenIFS
                        FESOM_USE_CPLNG: '"active"'
                        ECE_CPL_NEMO_LIM: '"false"'
                        ECE_CPL_FESOM_FESIM: '"false"'
                        ECE_AWI_CPL_FESOM: '"false"'

        res_level: ${resolution}${levels}
        oifsamip_fields: [A_SST, A_Ice_frac]

        coupling_fields:
                "[[oifsamip_fields-->FIELD]]":
                    grid: atma
                A_Runoff:
                    grid: atmr
                A_Calving:
                    grid: atmr

        input_files:
                ICMGG_INIT: ICMGG_INIT
                ICMGG_INIUA: ICMGG_INIUA
                ICMSH_INIT: ICMSH_INIT

        prepifs_dir: ${input_dir}/${res_level}/
        tl_o3_data_dir: ${input_dir}/${version}/climate/
        ICMGG_INIT_name: ""

        # Remove ICMCL_INIT forcing, which is only required for standalone simulations
        remove_forcing_files:
                - ICMCL_INIT


amip:
        pool_dir: ${general.pool_dir}

        nproc: 1
        omp_num_threads: ${computer.partitions.compute.cores_per_node}
        time_step: 86400

        coupling_fields:
                "[[amip_fields_send-->FIELD]]":
                        grid: AMIP

        grids:
                AMIP:
                        name: AMIP
                        nx: 360
                        ny: 180
                        oasis_grid_type: "LR"


#########################################################################################

# Settings for OASIS
oasis3mct:
        model_dir: ${general.model_dir}/oasis
        pool_dir: ${general.pool_dir}/oasis_experimental/
        input_dir: ${pool_dir}/cy${oifs.version}/${oifs.resolution}-AMIP/
        mct_version: 4.0
        norestart: "F"

        process_ordering:
                - amip
                - oifs

        required_plugins:
                - "git+https://github.com/esm-tools-plugins/oasis_rmp_rst_to_input"

        # lresume needs to be true to allow usage of flxatmos and sstocean
        # "restart" files in initial coupling time step
        # but only if the general model setup is a cold start (i.e. general.lresume = false)
        lresume: True
        ini_parent_date: "19500101" # not used, but needs to be present
        ini_parent_exp_id: "khw0030" # not used, but needs to be present
        ini_restart_dir: "${input_dir}"

        output_exchanged_vars: false

        time_step: 86400


        coupling_time_step: "${oasis3mct.time_step}"
        choose_general.version:
                'cy43':
                        coupling_target_fields:
                                rstos.nc:
                                        - 'A_SST:A_Ice_frac <--gauswgt_i-- AMIP_sst:AMIP_sic'

        coupling_directions:
                'AMIP->atma':
                        lag: 0
                        seq: 1


        coupling_methods:
                gauswgt_i:
                        time_transformation: instant
                        remapping:
                                gauswgt:
                                        search_bin: latitude
                                        nb_of_search_bins: 1
                                        nb_of_neighbours: 25
                                        weight: "0.1"

        input_files: {}

        input_in_work:
                rmp: rmp_*.nc
                areas: areas.nc
                masks: masks.nc
                grids: grids.nc

        input_sources:
                rmp: ${input_dir}/rmp_*.nc
                areas: ${input_dir}/areas.nc
                masks: ${input_dir}/masks.nc
                grids: ${input_dir}/grids.nc

        restart_in_files:
                rmp: rmp
                rstos.nc: rstos.nc

        restart_in_in_work:
                rmp: rmp_*.nc
                rstos.nc: rstos.nc

        choose_lresume:
                false:
                        choose_general.run_number:
                                1:
                                        add_input_files:
                                                rmp: rmp
                                                areas: areas
                                                masks: masks
                                                grids: grids
                true:
                        # If ini_restart_dir is not specified in the runscript and, therefore,
                        # it is not a branched off experiment add the / to the
                        # sources when the run_number is 1
                        load_restart_from_pool: "$(( '${input_dir}' == '${ini_restart_dir}' and ${general.run_number} == 1))"
                        choose_load_restart_from_pool:
                                true:
                                        add_restart_in_sources:
                                                rmp: ${input_dir}/rmp_*.nc
                                                rstos.nc: ${input_dir}/rstos.nc

        restart_in_sources:
                rmp: rmp_*.nc
                rstos.nc: rstos.nc

        restart_out_files:
                rmp: rmp
                rstos.nc: rstos.nc

        restart_out_in_work:
                rmp: rmp_*.nc
                rstos.nc: rstos.nc

        restart_out_sources:
                rmp: rmp_*.nc
                rstos.nc: rstos.nc


