#!/usr/bin/bash
#SBATCH --partition=batch
#SBATCH --time=00:20:00
#SBATCH --nodes=3
#SBATCH --output=/p/scratch/chhb19/mandresm/testing//run/oifsamip//oifsamip-TCO159L91_inital/log/oifsamip-TCO159L91_inital_oifsamip_compute_20000101-20000101.log --error=/p/scratch/chhb19/mandresm/testing//run/oifsamip//oifsamip-TCO159L91_inital/log/oifsamip-TCO159L91_inital_oifsamip_compute_20000101-20000101.log
#SBATCH --job-name=oifsamip-TCO159L91_inital
#SBATCH --account=hhb19
#SBATCH --mail-type=NONE
#SBATCH --exclusive

module --force purge
module use $OTHERSTAGES
module load Stages/2020
module load Intel/2020.2.254-GCC-9.3.0
module load ParaStationMPI/5.4.7-1
module load CMake
module load Python/3.8.5
module load imkl/2020.2.254

export LC_ALL=en_US.UTF-8
export TMPDIR=/tmp
export FC=mpifort
export F77=mpifort
export MPIFC=mpifort
export FCFLAGS=-free
export CC=mpicc
export CXX=mpic++
export MPIROOT="$(mpifort -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export IO_LIB_ROOT=/p/project/hirace/HPC_libraries/intel2020.2.254_parastation_5.4.7-1_20210427
export PATH=$IO_LIB_ROOT/bin:$PATH
export LD_LIBRARY_PATH=$IO_LIB_ROOT/lib:$LD_LIBRARY_PATH
export SZIPROOT=$IO_LIB_ROOT
export HDF5ROOT=$IO_LIB_ROOT
export HDF5_ROOT=$HDF5ROOT
export NETCDFROOT=$IO_LIB_ROOT
export NETCDFFROOT=$IO_LIB_ROOT
export ECCODESROOT=$IO_LIB_ROOT
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export OIFS_FFIXED=""
export GRIB_SAMPLES_PATH="$ECCODESROOT/share/eccodes/ifs_samples/grib1_mlgrib2/"
export DR_HOOK_IGNORE_SIGNALS=-1
export OMP_SCHEDULE=STATIC
export OMP_STACKSIZE=128M
export ACCOUNT=hhb19
export ESM_TESTING_DIR=/p/scratch/chhb19/mandresm/testing//run/oifsamip/
export MODEL_DIR=/p/scratch/chhb19/mandresm/testing//comp/oifsamip/oifsamip-cy43
export FESOM_USE_CPLNG="active"
export ECE_CPL_NEMO_LIM="false"
export ECE_CPL_FESOM_FESIM="false"
export ECE_AWI_CPL_FESOM="false"
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE

unset SLURM_DISTRIBUTION
unset SLURM_NTASKS
unset SLURM_NPROCS
unset SLURM_ARBITRARY_NODELIST

# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!

echo $(date +"%a %b  %e %T %Y") : compute 1 2000-01-01T00:00:00 6560 - start >> /p/scratch/chhb19/mandresm/testing//run/oifsamip//oifsamip-TCO159L91_inital/log//oifsamip-TCO159L91_inital_oifsamip.log

cd /p/scratch/chhb19/mandresm/testing//run/oifsamip//oifsamip-TCO159L91_inital/run_20000101-20000101/work/

#Creating hostlist for MPI + MPI&OMP heterogeneous parallel job
rm -f ./hostlist
export SLURM_HOSTFILE=/p/scratch/chhb19/mandresm/testing//run/oifsamip//oifsamip-TCO159L91_inital/run_20000101-20000101/work//hostlist
IFS=$'\n'; set -f
listnodes=($(< <( scontrol show hostnames $SLURM_JOB_NODELIST )))
unset IFS; set +f
rank=0
current_core=0
current_core_mpi=0
mpi_tasks_amip=1
omp_threads_amip=48
mpi_tasks_oifs=32
omp_threads_oifs=2
for model in amip oifs oasis3mct ;do
    eval nb_of_cores=\${mpi_tasks_${model}}
    eval nb_of_cores=$((${nb_of_cores}-1))
    for nb_proc_mpi in `seq 0 ${nb_of_cores}`; do
        (( index_host = current_core / 48 ))
        host_value=${listnodes[${index_host}]}
        (( slot =  current_core % 48 ))
        echo $host_value >> hostlist
        (( current_core = current_core + omp_threads_${model} ))
    done
done

time srun -l  --multi-prog hostfile_srun 2>&1 &

# Call to esm_runscript to start subjobs:
# ['tidy']
process=$! 
# Comment the following line if you don't want esm_runscripts to restart:
cd /p/scratch/chhb19/mandresm/testing//run/oifsamip//oifsamip-TCO159L91_inital/scripts/
esm_runscripts oifsamip-TCO159L91_inital.yaml -e oifsamip-TCO159L91_inital -t observe_compute -p ${process} -s 20000101 -r 1 -v  --open-run

echo $(date +"%a %b  %e %T %Y") : compute 1 2000-01-01T00:00:00 6560 - done >> /p/scratch/chhb19/mandresm/testing//run/oifsamip//oifsamip-TCO159L91_inital/log//oifsamip-TCO159L91_inital_oifsamip.log

wait
