[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "esm_tools"
version = "6.59.3"

requires-python = ">= 3.9"

dependencies = [
  "click==8.1.8",
  "pygithub==1.55",
  "colorama==0.4.5",
  "emoji==1.7.0",
  "f90nml==1.4.2",
  "gfw-creator==0.2.2",
  "gitpython==3.1.41",  # Maximum version for Python 3.6 support
  "jinja2==3.1.6",
  "loguru==0.6.0",
  "numpy>=1.19.5",  # Maximum version for Python 3.6 support
  "packaging==22.0",
  "pandas>=1.1.5",  # Correct compatiability with xarray for Python 3.6
  "psutil==5.9.1",
  "pytest==7.1.2",
  "pyyaml==6.0.1",
  "questionary==1.10.0",
  "ruamel.yaml==0.17.32",
  "ruamel.yaml.clib==0.2.7",
  "semver==2.13.0",
  "sqlalchemy>=1.4.39",
  "tabulate==0.8.10",
  "tqdm==4.66.3",
  "typing_extensions>=4.1.1",  # Maximum number for Python 3.6 support
  "xdgenvpy==2.3.5",
  "pydantic>=1.10.13",
  "h5netcdf>=0.8.1",
]

[project.optional-dependencies]
dev = [
  "black==23.3.0",
  "bumpversion",
  "ipdb==0.13.13",
  "isort==5.12.0",
  "pre-commit==4.5.0",
]

