components:
- xios-2.5-ece
- rnfmap-v1.1
- oifs-48r1
- fesom-2.7
- oasis3mct-5.0-smhi
coupling_changes:
- sed -i.bak 's/xios-2.5+/xios/g' oifs-48r1/bundle.yml
- sed -i.bak 's/xios-3.0/xios/g' oifs-48r1/bundle.yml
- sed -i.bak 's/xios\/build_ecearth/xios/g' oifs-48r1/bundle.yml
- sed -i.bak 's/oasis3-mct-5.2/oasis/g' oifs-48r1/bundle.yml
- sed -i.bak '/CPLNG_ACTIVE = /s/.FALSE./.TRUE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- sed -i.bak '/COUPLENEMOECE = /s/.TRUE./.FALSE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- sed -i.bak '/COUPLEFESOM2 = /s/.FALSE./.TRUE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- sed -i.bak '/COUPLENEMOFOCI = /s/.TRUE./.FALSE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- sed -i.bak '/LNEMOLIMGET = /s/.TRUE./.FALSE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- sed -i.bak '/LNEMOLIMPUT = /s/.TRUE./.FALSE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- sed -i.bak '/LNEMOLIMALB = /s/.FALSE./.TRUE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- sed -i.bak '/LNEMOLIMTEMP = /s/.FALSE./.TRUE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- sed -i.bak '/LNEMOLIMTHK = /s/.TRUE./.FALSE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- sed -i.bak '/LNEMOLIMCUR = /s/.FALSE./.TRUE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- sed -i.bak '/LNEMOSICOUP = /s/.FALSE./.TRUE./g' oifs-48r1/ifs-source/arpifs/module/yommcc.F90
- rm -f oifs-48r1/bundle.yml.bak
- rm -f oifs-48r1/ifs-source/arpifs/module/yommcc.F90.bak

