# Setup up compile and runtime environment i.e. what needs
# to be changed w.r.t the default config/machines/<computer>.yaml
#
#
# Setup up compile and runtime environment i.e. what needs
# to be changed w.r.t the default config/machines/<computer>.yaml



compiletime_environment_changes:
  choose_computer.name:
    juwels:
      add_export_vars:
        RNF_OASIS_BASE: '$(pwd)/oasis'
        RNF_OASIS_INCLUDE: '"-I$RNF_OASIS_BASE/build/lib/psmile -I$RNF_OASIS_BASE/build/lib/psmile/scrip -I$RNF_OASIS_BASE/build/lib/psmile/mct -I$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu"'
        RNF_OASIS_LIB: '"-L$RNF_OASIS_BASE/build/lib/psmile -L$RNF_OASIS_BASE/build/lib/psmile/scrip -L$RNF_OASIS_BASE/build/lib/psmile/mct -L$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"'
        # netcdf
        RNF_NETCDF_INCLUDE: '"-I$NETCDFROOT/include"'
        RNF_NETCDF_LIB: '"-L$NETCDFROOT/lib -lnetcdf"'
        RNF_NETCDFF_INCLUDE: '"-I$NETCDFFROOT/include"'
        RNF_NETCDFF_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
        # compilers and compile switches
        RNF_FFLAGS: '"-r8 -fp-model precise -align array32byte -O1 ${computer.OpenMP_flag} -xCORE_AVX2 -g -traceback -convert big_endian -fpe0"'
        RNF_CFLAGS: '"-r8 -fp-model precise -align array32byte -O1 ${computer.OpenMP_flag} -xCORE_AVX2 -g -traceback -convert big_endian -fpe0"'

    levante:
      add_export_vars:
        NETCDFROOT: "/sw/spack-levante/netcdf-c-4.8.1-2k3cmu"
        NETCDFFROOT: "/sw/spack-levante/netcdf-fortran-4.5.3-k6xq5g"
        NETCDF_Fortran_INCLUDE_DIRECTORIES: $NETCDFFROOT/include
        NETCDF_C_INCLUDE_DIRECTORIES: $NETCDFROOT/include
        # oasis
        RNF_OASIS_BASE: '$(pwd)/oasis'
        RNF_OASIS_INCLUDE: '"-I$RNF_OASIS_BASE/build/lib/psmile -I$RNF_OASIS_BASE/build/lib/psmile/scrip -I$RNF_OASIS_BASE/build/lib/psmile/mct -I$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu"'
        RNF_OASIS_LIB: '"-L$RNF_OASIS_BASE/build/lib/psmile -L$RNF_OASIS_BASE/build/lib/psmile/scrip -L$RNF_OASIS_BASE/build/lib/psmile/mct -L$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"'
        # netcdf
        RNF_NETCDF_INCLUDE: '"-I$NETCDFROOT/include"'
        RNF_NETCDF_LIB: '"-L$NETCDFROOT/lib -lnetcdf"'
        RNF_NETCDFF_INCLUDE: '"-I$NETCDFFROOT/include"'
        RNF_NETCDFF_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
        # compilers and compile switches
        RNF_FFLAGS: '"-r8 -fp-model precise -align array32byte -O3 -qopenmp -g -traceback -convert big_endian -march=core-avx2 -mtune=core-avx2"'
        RNF_CFLAGS: '"-fp-model precise -O3 -g -traceback -qopt-report=0 -fpe0 -qopenmp -march=core-avx2 -mtune=core-avx2"'

    albedo:
      add_export_vars:
        NETCDF_Fortran_INCLUDE_DIRECTORIES: $NETCDFFROOT/include
        NETCDF_C_INCLUDE_DIRECTORIES: $NETCDFROOT/include
        OASIS3MCT_FC_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
        # TODO: figure out whether those two are still needed
        ESM_NETCDF_C_DIR: "$NETCDFROOT"
        ESM_NETCDF_F_DIR: "$NETCDFFROOT"
        # oasis
        RNF_OASIS_BASE: '$(pwd)/oasis'
        RNF_OASIS_INCLUDE: '"-I$RNF_OASIS_BASE/build/lib/psmile -I$RNF_OASIS_BASE/build/lib/psmile/scrip -I$RNF_OASIS_BASE/build/lib/psmile/mct -I$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu"'
        RNF_OASIS_LIB: '"-L$RNF_OASIS_BASE/build/lib/psmile -L$RNF_OASIS_BASE/build/lib/psmile/scrip -L$RNF_OASIS_BASE/build/lib/psmile/mct -L$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"'
        # netcdf
        RNF_NETCDF_INCLUDE: '"-I$NETCDFROOT/include"'
        RNF_NETCDF_LIB: '"-L$NETCDFROOT/lib -lnetcdf"'
        RNF_NETCDFF_INCLUDE: '"-I$NETCDFFROOT/include"'
        RNF_NETCDFF_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
        # compilers and compile switches
        RNF_FFLAGS: '"-r8 -fp-model precise -align array32byte -O3 -qopenmp -g -traceback -convert big_endian -march=core-avx2 -mtune=core-avx2"' # -qoverride-limits -fast-transcendentals -m64  -fma -pc64"'
        RNF_CFLAGS: '"-fp-model precise -O3 -g -traceback -qopt-report=0 -fpe0 -qopenmp -march=core-avx2 -mtune=core-avx2"' # -qoverride-limits -fast-transcendentals -m64 -fma -pc64"'


    aleph:
      add_export_vars:
        # oasis
        RNF_OASIS_BASE: '$(pwd)/oasis'
        RNF_OASIS_INCLUDE: '"-I$RNF_OASIS_BASE/build/lib/psmile -I$RNF_OASIS_BASE/build/lib/psmile/scrip -I$RNF_OASIS_BASE/build/lib/psmile/mct -I$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu"'
        RNF_OASIS_LIB: '"-L$RNF_OASIS_BASE/build/lib/psmile -L$RNF_OASIS_BASE/build/lib/psmile/scrip -L$RNF_OASIS_BASE/build/lib/psmile/mct -L$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"'
        RNF_NETCDF_INCLUDE: '-I$NETCDF_DIR/include'
        RNF_NETCDF_LIB: '"-L$NETCDF_DIR/lib -lnetcdf"'
        RNF_NETCDFF_INCLUDE: '-I$NETCDF_DIR/include'
        RNF_NETCDFF_LIB: '"-L$NETCDF_DIR/lib -lnetcdff"'
        RNF_FC: '${computer.fc}'
        RNF_FFLAGS: '"-O2 -emf -hthread1 -hflex_mp=conservative -hfp1 -hadd_paren -hbyteswapio -J./ -hcpu=x86-skylake -U_CRAYFTN"'   #TODO: Test: -O3 -hfp3
        RNF_CFLAGS: '"-emf -O2 -hcpu=x86-skylake"'

