import glob
import os
import subprocess
import sys

import questionary
from loguru import logger

from esm_tools import user_error


class oasis:
    def __init__(
        self,
        nb_of_couplings=1,
        coupled_execs=["echam", "fesom"],
        runtime=1,
        debug_level=1,
        nnorest="F",
        mct_version="4.0",
        lucia=False,
    ):
        if isinstance(mct_version, tuple):
            pass
        elif isinstance(mct_version, int):
            mct_version = (mct_version, 0)
        elif isinstance(mct_version, float):
            mct_version = tuple(int(x) for x in str(mct_version).split("."))
        # PG: Fixup version to be tuples:
        elif isinstance(mct_version, str):
            mct_version = tuple(int(x) for x in mct_version.split("."))
        else:
            logger.error(
                "Init of Oasis needs the argument mct_version to be either a tuple or a string!",
            )
            sys.exit(1)
        self.namcouple = [
            "# This namcouple was automatically generated by the esm-tools (Python)"
        ]
        self.namcouple += [" $NFIELDS", "            " + str(nb_of_couplings), " $END"]
        exec_entry = ""
        for exe in coupled_execs:
            exec_entry = exec_entry + " " + exe
        exec_entry = str(len(coupled_execs)) + exec_entry
        self.namcouple += [" $NBMODEL", "            " + str(exec_entry), " $END"]
        self.namcouple += [" $RUNTIME", "           " + str(runtime), " $END"]
        if lucia:
            if mct_version >= (5, 0):
                self.namcouple += [" $NLOGPRT", "           " + str(debug_level) + " 0 1", " $END"]
            else:
                self.namcouple += [" $NLOGPRT", "           " + "1 -1", " $END"]
        else:
            if mct_version >= (5, 0):
                self.namcouple += [" $NLOGPRT", "           " + str(debug_level) + " 0 0", " $END"]
            else:
                self.namcouple += [" $NLOGPRT", "           " + "1", " $END"]
        if mct_version >= (4, 0):
            # If true, OASIS can start without restart files
            self.namcouple += [" $NNOREST", "           " + str(nnorest), " $END "]
        self.namcouple += [" $STRINGS"]
        self.namcouple += [
            "###############################################################################"
        ]
        self.namcouple += [
            "###############################################################################"
        ]
        self.next_coupling = 1
        self.name = "oasis3mct"

    def add_input_coupling(self, field_name, freq, field_filepath):
        self.namcouple += ["#"]
        nb = self.next_coupling
        self.namcouple += [
            f"{field_name} {field_name} {nb} {freq} 0 {field_filepath} INPUT"
        ]
        self.namcouple += "#"
        self.next_coupling += 1

    def add_coupling(
        self,
        lefts,
        lgrid,
        rights,
        rgrid,
        direction,
        transformation,
        restart_file,
        time_step,
        lresume,
        export_mode="DEFAULT",
    ):
        self.namcouple += ["#"]

        nb = self.next_coupling

        left = sep = ""
        for lefty in lefts:
            restart_out_file = lefty + "_"

            left += sep + lefty
            self.next_coupling += 1
            sep = ":"

        right = sep = ""
        for righty in rights:
            right += sep + righty
            sep = ":"

        if export_mode == "DEFAULT":
            if bool(lresume) is False:
                export_mode = "EXPOUT"
            else:
                export_mode = "EXPORTED"

        if not lresume and not direction.get('lag_overwrite'):
            lag = 0
        else:
            lag = direction.get('lag')

        # if a transformation method for CONSERV (e.g. GLOBAL) is set below,
        # increase seq (=number of lines describing the transformation) by 1
        # this part was broke, confused seq with nb of trafo lines

        seq = int(direction.get("seq", "2"))
        # if transformation.get("postprocessing", {}).get("conserv", {}).get("method"):
        #    seq += 1
        time_step = direction.get("coupling_time_step", time_step)

        p_rgrid = p_lgrid = "0"
        if "number_of_overlapping_points" in rgrid:
            p_rgrid = str(rgrid["number_of_overlapping_points"])
        if "number_of_overlapping_points" in lgrid:
            p_lgrid = str(lgrid["number_of_overlapping_points"])

        trafo_line = ""
        trafo_details = []

        alltimes = transformation.get("time_transformation", "bla")
        if not isinstance(alltimes, list):
            alltimes = [alltimes]
        for time in alltimes:
            detail_line = ""
            if time.lower() in [
                "stocha",
                "instant",
                "accumul",
                "average",
                "t_min",
                "t_max",
            ]:
                trafo_line = "LOCTRANS"
                detail_line = time.upper()
                trafo_details.append(detail_line.strip())

        allpres = transformation.get("preprocessing", "bla")
        if not isinstance(allpres, list):
            allpres = [allpres]
        for pre in allpres:
            detail_line = ""
            if isinstance(pre, dict):
                pre = list(pre.keys())[0]
            if pre.lower() == "checkin":
                trafo_line += " CHECKIN"
                detail_line = "INT = 1"
                trafo_details.append(detail_line.strip())
            elif pre.lower() == "blasold":
                trafo_line += " BLASOLD"
                coefficient = transformation["preprocessing"][pre].get("xmult", None)
                if not coefficient:
                    logger.error(
                        "xmult needs to be defined for preprocessing BLASOLD",
                    )
                    sys.exit(2)
                add_scalar = transformation["preprocessing"][pre].get(
                    "add_scalar", None
                )
                if not add_scalar:
                    logger.error(
                        "add_scalar needs to be defined (0 or 1) for preprocessing BLASOLD",
                    )
                    sys.exit(2)
                detail_line = str(coefficient) + " " + str(add_scalar)
                trafo_details.append(detail_line.strip())
                if str(add_scalar) == "1":
                    scalar_to_add = transformation["preprocessing"][pre].get(
                        "scalar_to_add", None
                    )
                    if not add_scalar:
                        logger.error(
                            "scalar_to_add needs to be defined if add_scalar is set to  1 for preprocessing BLASOLD",
                        )
                        sys.exit(2)
                    detail_line = " CONSTANT" + str(add_scalar)
                    trafo_details.append(detail_line.strip())

        alltrans = transformation.get("remapping", {"bla": "blub"})

        oyac = transformation.get("oyac", False)
        if oyac:  # OASIS with YAC interpolation library (OYAC)
            nb_stack = str(len(alltrans))
            oyac_io_per_node = str(rgrid["oyac_io_per_node"]).upper()

            trafo_line += " YAC"
            # TODO: Read new var nb_stack for number of interpolations in stack
            srcgridtype = str(rgrid["oyac_grid_type"]).upper()
            # TODO: We need not only src but also dst grid type
            dstgridtype = str(lgrid["oyac_grid_type"]).upper()
            translist = []
            for trans in alltrans:
                translist.append(trans)
            rmp_name = result = "_".join(translist)
            general_oyac_line = (
                srcgridtype.upper()
                + " "
                + dstgridtype.upper()
                + " "
                + nb_stack
                + " YAC_"
                + rmp_name.upper()
                + " "
                + oyac_io_per_node
            )
            trafo_details += [general_oyac_line.strip()]
            for trans in alltrans:
                transform = alltrans[trans]
                if trans.upper() == "CONSERV":
                    order = transform.get("order", None)
                    intersect_norm = transform.get("intersect_norm", None)
                    stack_line = (
                        trans.upper()
                        + " "
                        + order.upper()
                        + " "
                        + intersect_norm.upper()
                    )
                    trafo_details += [stack_line.strip()]
                elif trans.upper() == "NNN":
                    weighting = transform.get("weighting", None)
                    nb_of_neighbours = str(transform.get("nb_of_neighbours", None))
                    stack_line = (
                        trans.upper()
                        + " "
                        + weighting.upper()
                        + " "
                        + nb_of_neighbours.upper()
                    )
                    trafo_details += [stack_line.strip()]
                elif trans.upper() == "HCSBB":
                    stack_line = (
                        trans.upper()
                    )
                    trafo_details += [stack_line.strip()]

        else:  # OASIS with SCRIP interpolation library
            if not isinstance(alltrans, list):
                alltrans = [alltrans]
            for thistrans in alltrans:
                (trans, transform) = list(thistrans.items())[0]
                detail_line = ""
                if "mapping" == trans.lower():
                    trafo_line += " MAPPING"
                    mapname = transform.get("mapname", None)
                    if not mapname:
                        logger.error(
                            "mapname needs to be defined for transformation MAPPING",
                        )
                        sys.exit(2)
                    maploc = transform.get("map_regrid_on", "")
                    mapstrat = transform.get("mapstrategy", "")
                    detail_line = mapname + " " + maploc + " " + mapstrat
                    trafo_details.append(detail_line.strip())

                elif trans.lower() in [
                    "distwgt",
                    "bicubic",
                    "bilinear",
                    "gauswgt",
                    "conserv",
                    "loccunif",
                ]:
                    trafo_line += " SCRIPR"
                    srcgridtype = str(rgrid["oasis_grid_type"]).upper()
                    search_bin = transform.get("search_bin", None)
                    if not search_bin:
                        logger.error(
                            "search_bin (LATITUDE or LATLON) needs to be defined for transformations DISTWGT, GAUSWGT, BILINEAR, BICUBIC, LOCCUNIF",
                        )
                        sys.exit(2)
                    bins = transform.get("nb_of_search_bins", "1")
                    detail_line = (
                        trans.upper()
                        + " "
                        + srcgridtype.upper()
                        + " SCALAR "
                        + search_bin.upper()
                        + " "
                        + str(bins)
                    )
                    if trans.lower() in ["distwgt", "gauswgt", "loccunif"]:
                        nb_of_neighbours = transform.get("nb_of_neighbours", None)
                        if not nb_of_neighbours:
                            logger.error(
                                "nb_of_neighbours needs to be defined for transformations DISTWGT, GAUSWGT and LOCCUNIF",
                            )
                            sys.exit(2)
                        detail_line += " " + str(nb_of_neighbours)
                    if trans.lower() == "gauswgt":
                        weight = transform.get("weight", None)
                        if not weight:
                            logger.error(
                                "weight needs to be defined for transformation GAUSWGT",
                            )
                            sys.exit(2)
                        detail_line += " " + str(weight)
                    if trans.lower() == "conserv":
                        normalization = transform.get("normalization", None)
                        if not normalization:
                            logger.error(
                                "normalization (FRACAREA, DESTAREA or FRACNNEI) needs to be defined for transformations CONSERV",
                            )
                            sys.exit(2)
                        order = transform.get("order", None)
                        if not order:
                            logger.error(
                                "order (FIRST or SECOND) needs to be defined for transformation CONSERV",
                            )
                            sys.exit(2)
                        detail_line += " " + normalization.upper() + " " + order.upper()
                    trafo_details += [detail_line.strip()]
                elif trans.lower() in [
                    "loctrans",
                ]:
                    continue

        allpost = transformation.get("postprocessing", "bla")
        if not isinstance(allpost, list):
            allpost = list(allpost)
        for post in allpost:
            detail_line = ""
            if post.lower() == "conserv":
                trafo_line += " CONSERV"
                method = transformation["postprocessing"][post].get("method", None)
                if not method:
                    logger.error(
                        " a method (GLOBAL, GLBPOS, BASBAL or BASPOS) needs to be defined for postprocessing CONSERV",
                    )
                    sys.exit(2)
                algorithm = transformation["postprocessing"][post].get("algorithm", "")
                detail_line = method.upper() + " " + algorithm.lower()
                trafo_details.append(detail_line.strip())
            elif post.lower() == "checkout":
                trafo_line += " CHECKOUT"
                detail_line = "INT = 1"
                trafo_details.append(detail_line.strip())
            elif post.lower() == "blasnew":
                trafo_line += " BLASNEW"
                coefficient = transformation["postprocessing"][post].get("xmult", None)
                if not coefficient:
                    logger.error(
                        "xmult needs to be defined for postprocessing BLASNEW",
                    )
                    sys.exit(2)
                add_scalar = transformation["postprocessing"][post].get(
                    "add_scalar", None
                )
                if not add_scalar:
                    logger.error(
                        "add_scalar needs to be defined (0 or 1) for preprocessing BLASOLD",
                    )
                    sys.exit(2)
                detail_line = str(coefficient) + " " + str(add_scalar)
                trafo_detail.append(detail_line.strip())
                if str(add_scalar) == "1":
                    scalar_to_add = transformation["postprocessing"][post].get(
                        "scalar_to_add", None
                    )
                    if not add_scalar:
                        logger.error(
                            "scalar_to_add needs to be defined if add_scalar is set to  1 for postprocessing BLASNEW",
                        )
                        sys.exit(2)
                    detail_line = " CONSTANT" + str(add_scalar)
                    trafo_details.append(detail_line.strip())

        # Remove the first space in cases such as trafo_line = ' SCRIPR CONSERV'
        if trafo_line[0] == " ":
            trafo_line = trafo_line[1:]

        if oyac:
            nb_of_trafo_lines = len(trafo_details) - int(nb_stack)
        else:
            nb_of_trafo_lines = len(trafo_details)

        self.namcouple += [
            right
            + " "
            + left
            + " "
            + str(nb)
            + " "
            + str(time_step)
            + " "
            + str(nb_of_trafo_lines)
            + " "
            + str(restart_file)
            + " "
            + export_mode
        ]
        if lgrid and rgrid:
            self.namcouple += [
                str(rgrid["nx"])
                + " "
                + str(rgrid["ny"])
                + " "
                + str(lgrid["nx"])
                + " "
                + str(lgrid["ny"])
                + " "
                + rgrid["name"]
                + " "
                + lgrid["name"]
                + " LAG="
                + str(lag)
            ]

        self.namcouple += ["P " + p_rgrid + " P " + p_lgrid]
        self.namcouple += [trafo_line]
        for line in trafo_details:
            self.namcouple += [line]

        self.namcouple += ["#"]
        self.namcouple += ["#"]
        self.namcouple += ["#"]
        self.namcouple += [
            "###############################################################################"
        ]

    def print_config_files(self):
        for line in self.namcouple:
            logger.info(line)

    def add_output_file(self, lefts, rights, leftmodel, rightmodel, config):
        out_file = []

        coupling = self.next_coupling

        if self.next_coupling < 10:
            this_coupling = "0" + str(coupling)
        else:
            this_coupling = str(coupling)

        for lefty in lefts:
            out_file.append(lefty + "_" + leftmodel + "_" + this_coupling + ".nc")
        for righty in rights:
            out_file.append(righty + "_" + rightmodel + "_" + this_coupling + ".nc")

        self.next_coupling += 1

        if "outdata_files" not in config:
            config["outdata_files"] = {}
        if "outdata_in_work" not in config:
            config["outdata_in_work"] = {}
        if "outdata_sources" not in config:
            config["outdata_sources"] = {}

        for thisfile in out_file:
            config["outdata_files"][thisfile] = thisfile
            config["outdata_in_work"][thisfile] = thisfile
            config["outdata_sources"][thisfile] = thisfile

    def add_restart_files(self, restart_file_label, fconfig):
        """
        Handles the special restart case of the coupling fields.

        Cases
        -----
        1. If this run is a restart but not a branch-off experiment, set the source to
            be the same as defined by the user in ``restart_in_sources`` or the same
            as the name coming from ``coupling_<target/input>_fields``, if the first is
            missing (the normal case).
        2. Same as case 1 but with the time stamp added to the name of the restart file
            to make sure the correct file (and not a link to the last restart file made)
            is loaded for the branch-off experiment. This option uses the
            non-timestamped version of the file when only one file is found (e.g. the
            parent simulation only has one run, or the files are taken for the first
            run from the pool, as in AWICM3).

        Parameters
        ----------
        restart_file_label : str
            The file's label (not the file name itself!). Used to retrieve the
            file's source and target path. As defined in the keys of
            ``coupling_target_fields`` or ``coupling_input_fields`` in the yamls
        fconfig : ConfigSetup
            The complete simulation configuration.
        """

        config = fconfig[self.name]
        gconfig = fconfig["general"]
        is_runtime = gconfig["execution_mode"] == "run"
        enddate = "_" + gconfig["end_date"].format(
            form=9, givenph=False, givenpm=False, givenps=False
        )
        parentdate = "_" + config["parent_date"].format(
            form=9, givenph=False, givenpm=False, givenps=False
        )

        if "restart_out_files" not in config:
            config["restart_out_files"] = {}
        if "restart_out_in_work" not in config:
            config["restart_out_in_work"] = {}
        if "restart_out_sources" not in config:
            config["restart_out_sources"] = {}

        if "restart_in_files" not in config:
            config["restart_in_files"] = {}
        if "restart_in_in_work" not in config:
            config["restart_in_in_work"] = {}
        if "restart_in_sources" not in config:
            config["restart_in_sources"] = {}

        # Find the actual path of the restart
        restart_file_path = config["restart_in_sources"].get(restart_file_label, None)
        # Find the actual name of the restart: if a path is given in restart_in_sources
        # get the basename of that path, otherwise assign the file label also as name
        # of the file (coming from ``coupling_<target/input>_fields``)
        if restart_file_path:
            restart_file = os.path.basename(restart_file_label)
        else:
            restart_file = restart_file_label

        config["restart_out_files"][restart_file_label] = restart_file
        config["restart_out_files"][restart_file_label + "_recv"] = (
            restart_file + "_recv"
        )

        config["restart_out_in_work"][restart_file_label] = restart_file  # + enddate
        config["restart_out_in_work"][restart_file_label + "_recv"] = (
            restart_file + "_recv"
        )  # + enddate

        config["restart_out_sources"][restart_file_label] = restart_file
        config["restart_out_sources"][restart_file_label + "_recv"] = (
            restart_file + "_recv"
        )

        config["restart_in_files"][restart_file_label] = restart_file
        config["restart_in_in_work"][restart_file_label] = restart_file

        # In case of a branch-off experiment -> use the correct oasis restart files:
        # Not the soft link to the last, but the actual one for the branch-off date
        if (
            gconfig["run_number"] == 1
            and config["lresume"]
            and gconfig["jobtype"] == "prepcompute"
            and config.get("norestart", "F") == "F"
        ):
            # If they do not exist, define ``ini_restart_date`` and ``ini_restart_dir``
            # based on ``ini_parent_date`` and ``ini_parent_dir``
            if "ini_parent_date" in config and "ini_restart_date" not in config:
                config["ini_restart_date"] = config["ini_parent_date"]
            if "ini_parent_dir" in config and "ini_restart_dir" not in config:
                config["ini_restart_dir"] = config["ini_parent_dir"]
            # If the restart file path is not defined, or it's not an absolute path to
            # the file, set it to be the same as the ini_restart_dir
            if not restart_file_path or restart_file_path == restart_file:
                restart_file_path = f"{config['ini_restart_dir']}/{restart_file}"
            # If set in config (oasis):
            if "ini_restart_dir" in config and "ini_restart_date" in config:
                # check if restart file with ini_restart_date in filename is in the restart
                # folder of the parent experiment to be branched off from:
                glob_search_file = (
                    f"{config['ini_restart_dir']}{restart_file}*"
                    f"{config['ini_restart_date'].year}"
                    f"{config['ini_restart_date'].month:02}"
                    f"{config['ini_restart_date'].day:02}"
                )
            else:
                glob_search_file = restart_file_path

            # add support for oasis_date_stamp (which for some reason does
            # not work anymore after awi-geomar merge in 2025 without the two lines below)
            # reason unknown, but the entire section here should be revised soon anyways 
            if config.get('oasis_date_stamp'):
                glob_search_file = restart_file_path

            glob_restart_file = glob.glob(glob_search_file)
            glob_restart_file.sort()
            if restart_file and is_runtime:
                # If there are more than one file found let the user decide which one to take
                if len(glob_restart_file) == 1:
                    restart_file = os.path.basename(glob_restart_file[0])
                elif len(glob_restart_file) == 0:
                    restart_file = restart_file_path
                    # in case config["restart_in_sources"] are given explicitely 
                    # AND are not absolute paths as e.g in FOCI
                    # ini_parent_dir: "${general.ini_parent_dir}/oasis3mct/"
                    #    restart_in_sources: sstocean_${parent_expid}_...
                    # we need to check for the full path as well 
                    # btw it was a nightmare to track this down
                    if not os.path.isfile(restart_file) and not os.path.isfile(f"{config['ini_restart_dir']}/{restart_file}"):
                        user_error(
                            "Restart file missing",
                            f"No OASIS restart file for ``{restart_file_label}`` found "
                            f"matching the pattern ``{glob_search_file}`` nor "
                            f"``{restart_file}``",
                        )
                else:
                    if not gconfig["isinteractive"]:
                        # If more than one restart file found that matches ini_restart_date,
                        # ask the user to select from the result list:
                        message = (
                            "More than one OASIS restart file was found for "
                            "your branchoff experiment that matches the "
                            "ini_restart_date you selected. Please select "
                            "one of the following OASIS restart files:"
                        )
                        answers = questionary.form(
                            restarts=questionary.select(
                                message, choices=glob_restart_file
                            )
                        ).ask()
                        restart_file = answers["restarts"]

            config["restart_in_sources"][restart_file_label] = restart_file

        if restart_file_label not in config["restart_in_sources"]:
            config["restart_in_sources"][restart_file_label] = restart_file

    def prepare_restarts(self, restart_file, all_fields, models, config):
        """
        Prepare OASIS restart files by merging EXPOUT files.
        
        Parameters
        ----------
        restart_file : str
            Name of the restart file to create
        all_fields : list
            List of field names
        models : list
            List of model names
        config : dict
            Configuration dictionary
        
        Note
        ----
        For bidirectional couplings with LOCTRANS, use merge_restart_files()
        after both prepare_restarts calls to merge _recv into main file.
        """
        enddate = "_" + config["general"]["end_date"].format(
            form=9, givenph=False, givenpm=False, givenps=False
        )
        # enddate = "_" + str(config["general"]["end_date"].year) + str(config["general"]["end_date"].month) + str(config["general"]["end_date"].day)

        logger.info("Preparing oasis restart files from initial run...")
        # Assign an exe per model
        exes = [config[model]["executable"] for model in models]
        logger.info(f"{restart_file}, {all_fields}, {models}, {exes}")
        cwd = os.getcwd()
        os.chdir(config["general"]["thisrun_work_dir"])
        filelist = ""
        # Collect coupling numbers from the specified fields to find all related EXPOUT files
        # This handles bidirectional LOCTRANS+EXPOUT where both directions write to same restart
        processed_files = set()
        coupling_numbers = set()
        
        # First pass: identify coupling numbers from specified fields
        initial_couplings = set()
        for field, model, exe in zip(all_fields, models, exes):
            field_files = glob.glob(field + "_" + exe + "_*.nc")
            for f in field_files:
                # Extract coupling number (e.g., "10" from "LAILVeg_OpenIFS_10.nc")
                parts = f.rsplit('_', 1)
                if len(parts) == 2 and parts[1].endswith('.nc'):
                    coupling_num = parts[1][:-3]
                    initial_couplings.add((exe, coupling_num))
        
        logger.info(f"Initial coupling numbers for {restart_file}: {initial_couplings}")
        
        # Second pass: find ALL executables writing to these coupling numbers
        # (handles bidirectional EXPOUT where sending model isn't in all_fields)
        for exe, coupling_num in initial_couplings:
            # Find all files with this coupling number, regardless of exe
            all_with_coupling = glob.glob("*_*_" + coupling_num + ".nc")
            for f in all_with_coupling:
                # Extract executable from filename (e.g., "lpjg" from "GUE_LLAI_lpjg_10.nc")
                parts = f.rsplit('_', 2)
                if len(parts) >= 3:
                    file_exe = parts[-2]
                    coupling_numbers.add((file_exe, coupling_num))
        
        logger.info(f"All coupling numbers for {restart_file}: {coupling_numbers}")
        
        # Third pass: process all files matching these (exe, coupling_number) pairs
        for exe, coupling_num in coupling_numbers:
            # Find ALL fields with this exe and coupling number (handles bidirectional EXPOUT)
            matching_files = glob.glob("*_" + exe + "_" + coupling_num + ".nc")
            logger.info(f"Including all files for {exe} coupling {coupling_num}: {matching_files}")
            
            for thisfile in matching_files:
                # Skip if already processed
                if thisfile in processed_files:
                    continue
                processed_files.add(thisfile)

                logger.info(
                    "cdo showtime " + thisfile + " 2>/dev/null | head -n 1 | wc -w",
                )

                lasttimestep = (
                    subprocess.check_output(
                        "cdo showtime " + thisfile + " 2>/dev/null | head -n 1 | wc -w",
                        shell=True,
                    )
                    .decode("utf-8")
                    .rstrip()
                )
                # Extract field name from filename (e.g., "T2MVeg" from "T2MVeg_OpenIFS_11.nc")
                field_from_file = thisfile.rsplit('_', 2)[0]
                
                logger.info(
                    "cdo -O seltimestep,"
                    + str(lasttimestep)
                    + " "
                    + thisfile
                    + " onlyonetimestep.nc",
                )
                os.system(
                    "cdo -O seltimestep,"
                    + str(lasttimestep)
                    + " "
                    + thisfile
                    + " onlyonetimestep.nc"
                )
                logger.info(
                    "ncwa -O -a time onlyonetimestep.nc notimestep_" + field_from_file + ".nc",
                )
                os.system(
                    "ncwa -O -a time onlyonetimestep.nc notimestep_" + field_from_file + ".nc"
                )
                filelist += "notimestep_" + field_from_file + ".nc "
                logger.info(filelist)
        # MA: -O flag added to overwrite oasis restart files in case oasis creats them
        # before (i.e. when using LOCTRANS)
        if os.path.isfile(restart_file):
            logger.debug(f"{restart_file} already exits, overwriting")

        cdo_merge_command = f"cdo -O -f nc4c merge {filelist} {restart_file}" # {enddate}"
        logger.info(cdo_merge_command)
        exit_code = os.system(cdo_merge_command)
        if exit_code != 0:
            cdo_merge_command = f"cdo -O merge {filelist} {restart_file}" # {enddate}"
            logger.warning("nc4c merge failed, trying without it...")
            logger.info(cdo_merge_command)
            os.system(cdo_merge_command)
        
        rmlist = glob.glob("notimestep*")
        rmlist.append("onlyonetimestep.nc")
        for rmfile in rmlist:
            logger.info("rm " + rmfile)
            os.system("rm " + rmfile)
        os.chdir(cwd)

    def merge_restart_files(self, restart_file, config):
        """
        Merge _recv restart file into main restart file for bidirectional couplings.
        This is called AFTER both restart files have been created.
        
        Parameters
        ----------
        restart_file : str
            Name of the main restart file
        config : dict
            Configuration dictionary
        """
        cwd = os.getcwd()
        os.chdir(config["general"]["thisrun_work_dir"])
        
        recv_file = restart_file + "_recv"
        if os.path.isfile(recv_file) and os.path.isfile(restart_file):
            logger.info(f"Merging {recv_file} into {restart_file} for bidirectional restart")
            temp_file = restart_file + ".tmp"
            merge_cmd = f"cdo -O -f nc4c merge {restart_file} {recv_file} {temp_file}"
            logger.info(merge_cmd)
            exit_code = os.system(merge_cmd)
            if exit_code != 0:
                merge_cmd = f"cdo -O merge {restart_file} {recv_file} {temp_file}"
                logger.warning("nc4c merge failed, trying without it...")
                logger.info(merge_cmd)
                exit_code = os.system(merge_cmd)
            if exit_code == 0:
                # Replace original with merged file
                os.system(f"mv {temp_file} {restart_file}")
                logger.info(f"Successfully merged {recv_file} into {restart_file}")
            else:
                logger.error(f"Failed to merge {recv_file} into {restart_file}")
        else:
            logger.warning(f"Cannot merge: {restart_file}={os.path.isfile(restart_file)}, {recv_file}={os.path.isfile(recv_file)}")
        
        os.chdir(cwd)

    def finalize(self, destination_dir):
        self.namcouple += [" $END"]
        endline = ""
        with open(destination_dir + "/namcouple", "w") as namcouple:
            for line in self.namcouple:
                namcouple.write(endline)
                namcouple.write(line)
                endline = "\n"
