#
# AMIP Reader YAML file
#

amip:
    model: amip
    executable: amip
    execution_command: amip

    description: |
            AMIP forcing reader taken from EC-Earth
    version: v1
    destination: amip-forcing

    ##
    ## Compile information
    ##
    clean_command: rm -rf bin; cd src; make clean; cd ..
    comp_command: rm -rf bin; mkdir bin; cd src; make ; cd .. ; cp bin/amip-forcing.exe ./bin/amip
    git-repository: https://gitlab.dkrz.de/ec-earth/amip-forcing-ece4.git
    install_bins: bin/amip
    ##
    ## Directories
    ##
    model_dir: ${general.model_dir}
    bin_dir: ${model_dir}/bin
    pool_dir: "${computer.pool_directories.pool}"
    input_dir: "${pool_dir}/amip-forcing/"
    namelist_dir: ${general.esm_namelist_dir}/amip/

    parent_expid: "test"

    resolution: 360x180

    generate_namelist: 1

    restart: 1
    restart_rate: 1
    restart_unit: 'months'

    namelists:
            - "namelist.amip"

    mip: "cmip7"

    choose_resolution:
            360x180:
                    nx: 360
                    ny: 180

    nproca: 1
    nprocb: 1

    runtime_seconds: "$(( $((${end_date} + 1days)) - ${start_date} ))"

    lresume: false

    bin_sources:
            bin: ${bin_dir}/${executable}

    config_sources:
            namelist.amip: "${namelist_dir}/namelist.amip"

    choose_mip:
        "cmip6":
            input_in_work:
                sst_forcing: "tosbcs_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-0_gs1x1_187001-201512.nc"
                sic_forcing: "siconcbcs_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-0_gs1x1_187001-201512.nc"
            input_sources:
                sst_forcing: "${input_dir}/tosbcs_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-0_gs1x1_187001-201512.nc"
                sic_forcing: "${input_dir}/siconcbcs_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-0_gs1x1_187001-201512.nc"
            sstvarname: "tosbcs"
            siconcvarname: "siconcbcs"
        "cmip7":
            input_in_work:
                sst_forcing: "tos_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-10_gn_187001-202212.nc"
                sic_forcing: "siconc_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-10_gn_187001-202212.nc"
            input_sources:
                sst_forcing: "${input_dir}/tos_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-10_gn_187001-202212.nc"
                sic_forcing: "${input_dir}/siconc_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-10_gn_187001-202212.nc"
            sstvarname: "tos"
            siconcvarname: "siconc"

    input_files:
            sst_forcing: sst_forcing
            sic_forcing: sic_forcing

    coupling_fields:
            "[[amip_fields_send-->FIELD]]":
                    grid: AMIP

    namelist_changes:
            namelist.amip:
                    NAMAMIP:
                            RunLengthSec: "${runtime_seconds}"
                            TimeStepSec: "86400"
                            FixYear: "0"
                            StartYear: "1850"
                            FileListSST: ${input_in_work.sst_forcing}
                            FileListSIC: ${input_in_work.sic_forcing}
                            sstvarname: ${sstvarname}
                            siconcvarname: ${siconcvarname}

    grids:
            AMIP:
                    name: AMIP
                    nx: 360
                    ny: 180
                    oasis_grid_type: "LR"

    amip_fields_send: [AMIP_sst,AMIP_sic]

computer:
    #
    # Setup up compile and run environment i.e. what needs
    # to be changed w.r.t the default config/machines/<computer>.yaml
    #
    choose_general.execution_mode:
        compile:
            add_export_vars:
                NETCDF_Fortran_INCLUDE_DIRECTORIES: $NETCDFFROOT/include
                # OASIS
                OIFS_OASIS_BASE: "$(pwd)/oasis"
                OIFS_OASIS_INCLUDE: '"-I$OIFS_OASIS_BASE/build/lib/psmile -I$OIFS_OASIS_BASE/build/lib/psmile/scrip -I$OIFS_OASIS_BASE/build/lib/psmile/mct -I$OIFS_OASIS_BASE/build/lib/psmile/mct/mpeu ${oasis3mct.yac_inc_path}"'
                OIFS_OASIS_LIB: '"-L$OIFS_OASIS_BASE/build/lib/psmile -L$OIFS_OASIS_BASE/build/lib/psmile/scrip -L$OIFS_OASIS_BASE/build/lib/psmile/mct -L$OIFS_OASIS_BASE/build/lib/psmile/mct/mpeu ${oasis3mct.yac_lib_path} -lpsmile -lmct -lmpeu -lscrip ${oasis3mct.yac_libs}"'
                # netcdf
                OIFS_NETCDF_INCLUDE: '"-I$NETCDFROOT/include"'
                OIFS_NETCDF_LIB: '"-L$NETCDFROOT/lib -lnetcdf"'
                OIFS_NETCDFF_INCLUDE: '"-I$NETCDFFROOT/include"'
                OIFS_NETCDFF_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
                # compilers and compile switches
                OIFS_FC: '$FC'
                OIFS_FFIXED: '""'
                OIFS_FCDEFS: '"BLAS LITTLE LINUX INTEGER_IS_INT"'
                OIFS_MPI_LIB: '"$MPI_LIB"'
                OIFS_CC: '$CC'
                OIFS_CCDEFS: '"LINUX LITTLE INTEGER_IS_INT _ABI64 BLAS _OPENMP"'

            choose_computer.compiler_mpi:
                gnu11_ompi4:
                    add_export_vars:
                        OIFS_FFLAGS: '"-fdefault-real-8 -march=core-avx2 -mtune=core-avx2 -O3 -fopenmp -g -fbacktrace -fconvert=big-endian"'
                        OIFS_CFLAGS: '"-march=core-avx2 -mtune=core-avx2 -O3 -fopenmp -g -fbacktrace"'
                intel2022_openmpi:
                    add_export_vars:
                        OIFS_FFLAGS: '"-r8 -fp-model precise -align array32byte -O3 -qopenmp -g -traceback -convert big_endian -march=core-avx2 -mtune=core-avx2"'
                        OIFS_CFLAGS: '"-fp-model precise -O3 -g -traceback -qopt-report=0 -fpe0 -qopenmp -march=core-avx2 -mtune=core-avx2"'
                        OIFS_LFLAGS: '"$MPI_LIB -qopenmp"'
