# WARNING: To be use only with FESOM 2.1
choose_asforcing:
        CORE2:
                leapyear: false
                forcing_folder: "CORE2"

                Ce_atm_oce: 1.75e-3
                Ch_atm_oce: 1.75e-3
                Cd_atm_oce: 1.0e-3
                Ce_atm_ice: 1.75e-3
                Ch_atm_ice: 1.75e-3
                Cd_atm_ice: 1.2e-3

                AOMIP_drag_coeff: False
                ncar_bulk_formulae: True
                ncar_bulk_z_wind: 10.0
                ncar_bulk_z_tair: 10.0
                ncar_bulk_z_shum: 10.0

                xwind_prefix: "u_10."
                ywind_prefix: "v_10."
                humi_prefix: "q_10."
                qsr_prefix: "ncar_rad."
                qlw_prefix: "ncar_rad."
                tair_prefix: "t_10."
                prec_prefix: "ncar_precip."
                snow_prefix: "ncar_precip."
                mslp_prefix: "slp."

                nm_xwind_var: "U_10_MOD"
                nm_ywind_var: "V_10_MOD"
                nm_humi_var: "Q_10_MOD"
                nm_qsr_var: "SWDN_MOD"
                nm_qlw_var: "LWDN_MOD"
                nm_tair_var: "T_10_MOD"
                nm_prec_var: "RAIN"
                nm_snow_var: "SNOW"
                nm_mslp_var: "SLP"

                nm_nc_iyear: 1948
                nm_nc_imm: 1
                nm_nc_idd: 1
                nm_nc_freq: 1
                nm_nc_tmid: 1
                l_xwind: True
                l_ywind: True
                l_humi: True
                l_qsr: True
                l_qlw: True
                l_tair: True
                l_prec: True
                l_mslp: False
                l_cloud: False
                l_snow: True

                runoff_file: "runoff.nc"
                sss_data_file: "PHC2_salx.nc"

                runoff_data_source: 'CORE2'
                sss_data_source: 'CORE2'

        JRA55:
                leapyear: true
                forcing_folder: "/JRA55-do-v1.4.0/"

                Ce_atm_oce: 1.75e-3
                Ch_atm_oce: 1.75e-3
                Cd_atm_oce: 1.0e-3
                Ce_atm_ice: 1.75e-3
                Ch_atm_ice: 1.75e-3
                Cd_atm_ice: 1.2e-3

                AOMIP_drag_coeff: False
                ncar_bulk_formulae: True
                ncar_bulk_z_wind: 10.0
                ncar_bulk_z_tair: 10.0
                ncar_bulk_z_shum: 10.0

                xwind_prefix: "uas."
                ywind_prefix: "vas."
                humi_prefix: "huss."
                qsr_prefix: "rsds."
                qlw_prefix: "rlds."
                tair_prefix: "tas."
                prec_prefix: "prra."
                snow_prefix: "prsn."
                mslp_prefix: "psl."

                nm_xwind_var: "uas"
                nm_ywind_var: "vas"
                nm_humi_var: "huss"
                nm_qsr_var: "rsds"
                nm_qlw_var: "rlds"
                nm_tair_var: "tas"
                nm_prec_var: "prra"
                nm_snow_var: "prsn"
                nm_mslp_var: "psl"

                nm_nc_iyear: 1900
                nm_nc_imm: 1
                nm_nc_idd: 1
                nm_nc_freq: 1
                nm_nc_tmid: 0
                l_xwind: True
                l_ywind: True
                l_humi: True
                l_qsr: True
                l_qlw: True
                l_tair: True
                l_prec: True
                l_mslp: False
                l_cloud: False
                l_snow: True

                runoff_file: "CORE2_runoff.nc"
                sss_data_file: "PHC2_salx.nc"

                runoff_data_source: 'CORE2'
                sss_data_source: 'CORE2'

        ERA5:
                leapyear: true
                forcing_folder: "/ERA5/"

                Ce_atm_oce: 1.75e-3
                Ch_atm_oce: 1.75e-3
                Cd_atm_oce: 1.0e-3
                Ce_atm_ice: 1.75e-3
                Ch_atm_ice: 1.75e-3
                Cd_atm_ice: 1.2e-3

                AOMIP_drag_coeff: False
                ncar_bulk_formulae: True
                ncar_bulk_z_wind: 10.0
                ncar_bulk_z_tair: 2.0
                ncar_bulk_z_shum: 2.0

                xwind_prefix: "u."
                ywind_prefix: "v."
                humi_prefix: "q."
                qsr_prefix: "ssrd."
                qlw_prefix: "strd."
                tair_prefix: "t2m."
                prec_prefix: "rf."
                snow_prefix: "sf."
                mslp_prefix: "sp."

                nm_xwind_var: "u"
                nm_ywind_var: "v"
                nm_humi_var: "q"
                nm_qsr_var: "ssrd"
                nm_qlw_var: "strd"
                nm_tair_var: "t2m"
                nm_prec_var: "rf"
                nm_snow_var: "sf"
                nm_mslp_var: "sp"

                nm_nc_iyear: 1900
                nm_nc_imm: 1
                nm_nc_idd: 1
                nm_nc_freq: 1
                nm_nc_tmid: 0
                l_xwind: True
                l_ywind: True
                l_humi: True
                l_qsr: True
                l_qlw: True
                l_tair: True
                l_prec: True
                l_mslp: False
                l_cloud: False
                l_snow: True

                runoff_file: "CORE2_runoff.nc"
                sss_data_file: "PHC2_salx.nc"

                runoff_data_source: 'CORE2'
                sss_data_source: 'CORE2'

        ECHAM5:
                leapyear: true

        RYF58-83:
                leapyear: false
                forcing_folder: "/RYF_Miriam/"

                Ce_atm_oce: 1.75e-3
                Ch_atm_oce: 1.75e-3
                Cd_atm_oce: 1.0e-3
                Ce_atm_ice: 1.75e-3
                Ch_atm_ice: 1.75e-3
                Cd_atm_ice: 1.2e-3

                AOMIP_drag_coeff: False
                ncar_bulk_formulae: True
                ncar_bulk_z_wind: 10.0
                ncar_bulk_z_tair: 10.0
                ncar_bulk_z_shum: 10.0

                xwind_prefix: "uas."
                ywind_prefix: "vas."
                humi_prefix: "huss."
                qsr_prefix: "rsds."
                qlw_prefix: "rlds."
                tair_prefix: "tas."
                prec_prefix: "prra."
                snow_prefix: "prsn."
                mslp_prefix: "psl."

                nm_xwind_var: "uas"
                nm_ywind_var: "vas"
                nm_humi_var: "huss"
                nm_qsr_var: "rsds"
                nm_qlw_var: "rlds"
                nm_tair_var: "tas"
                nm_prec_var: "prra"
                nm_snow_var: "prsn"
                nm_mslp_var: "psl"

                nm_nc_iyear: 1900
                nm_nc_imm: 1
                nm_nc_idd: 1
                nm_nc_freq: 1
                nm_nc_tmid: 0
                l_xwind: True
                l_ywind: True
                l_humi: True
                l_qsr: True
                l_qlw: True
                l_tair: True
                l_prec: True
                l_mslp: False
                l_cloud: False
                l_snow: True

                runoff_file: "CORE2_runoff.nc"
                sss_data_file: "PHC2_salx.nc"

                runoff_data_source: 'CORE2'
                sss_data_source: 'CORE2'
                

