#!/bin/sh
#PBS -q iccp
#PBS -l walltime=00:30:00
#PBS -l nodes=1
#PBS -j oe -o /scratch/awi/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/log/awicm3-frontiers-TCO159L91-CORE2_initial_awicm3_postprocessing_20000101-20000101.log
#PBS -N awicm3-frontiers-TCO159L91-CORE2_initial
#PBS -A iccp

module unload craype
module load craype/2.6.2
module load PrgEnv-cray/6.0.4
module load pbs
module load cray-mpich/7.7.3
module load craype-x86-skylake
module load cmake/3.14.0
module load cray-hdf5-parallel/1.10.2.0
module load cray-netcdf-hdf5parallel/4.6.1.3
module load cdo/1.9.5
module load fftw/2.1.5.9
module load nco/4.9.4
module load proj4/5.1.0
module load python/3.9.1
module list

export LC_ALL=en_US.UTF-8
export HDF5ROOT=$HDF5_ROOT
export NETCDFFROOT=$NETCDF_DIR
export NETCDFROOT=$NETCDF_DIR
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_LIBRARIES=$NETCDFROOT/lib
export PERL5LIB=/usr/lib64/perl5
export XML2ROOT=/usr
export ZLIBROOT=/usr
export TMPDIR=/tmp
export PMI_LABEL_ERROUT=1
export ECCODESROOT=/proj/awiiccp/software/ecmwf/eccodes_cce_mpich
export MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_CRAY_OPT_THREAD_SYNC=0
export MPICH_OPT_THREAD_SYNC=0
export ENABLE_ALEPH_CRAYMPICH_WORKAROUNDS=
export FC=ftn
export CC=cc
export CXX=CC
export CRAYPE_LINK_TYPE=dynamic
export OASIS_FFLAGS=-emf
export GRIB_SAMPLES_PATH="$ECCODESROOT/share/eccodes/ifs_samples/grib1_mlgrib2/"
export DR_HOOK_IGNORE_SIGNALS=-1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ECCODESROOT/lib:$PROJ4_DIR/lib
export PATH=$ECCODESROOT/bin:${PATH}
export ACCOUNT=iccp
export ESM_TESTING_DIR=/scratch/awi/mandresm/testing//run/awicm3/
export MODEL_DIR=/scratch/awi/mandresm/testing//comp/awicm3/awicm3-frontiers
export FESOM_USE_CPLNG="active"
export ECE_CPL_NEMO_LIM="false"
export ECE_CPL_FESOM_FESIM="true"
export ECE_AWI_CPL_FESOM="true"
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!

echo $(date +"%a %b  %e %T %Y") : postprocessing_oifs 1 2000-01-01T00:00:00 329543.sdb - start >> /scratch/awi/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/log//awicm3-frontiers-TCO159L91-CORE2_initial_awicm3.log

cd /scratch/awi/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/run_20000101-20000101/work/
time aprun -n 1 -N 1 -d 1 env OMP_NUM_THREADS=1 env PMI_LABEL_ERROUT_FORMAT="[DATAPROCESS]%l:" /mnt/lustre/home/awiiccp/esm_tools/configs/.//setups/awicm3/postprocessing.sh /scratch/awi/mandresm/testing//run/awicm3//awicm3-frontiers-TCO159L91-CORE2_initial/outdata/oifs/ 20000101 2>&1 &

wait
