components:
- oifs-43r3-foci30
- nemo-eORCA025_Z75_SI3_COUPLED
- oasis3mct-EM21
- rnfmap-foci211
#- xios-trunk_oasis
coupling_changes:
- sed -i '/COUPLENEMOECE = /s/.TRUE./.FALSE./g' oifs-43r3-foci30/src/ifs/module/yommcc.F90
- sed -i '/COUPLEFESOM2 = /s/.TRUE./.FALSE./g' oifs-43r3-foci30/src/ifs/module/yommcc.F90
- sed -i '/COUPLENEMOFOCI = /s/.FALSE./.TRUE./g' oifs-43r3-foci30/src/ifs/module/yommcc.F90
