available_versions:
- 6.3.04p1-esm-interface-yac
- 6.3.05p2
- 6.3.05p2-foci
- 6.3.02p4
- 6.3.04p1-esm-interface
- 6.3.05p2-concurrent_radiation
- 6.3.04p1-paleodyn
- 6.3.04p1
branch: ${echam.version}
choose_version:
  6.3.02p4:
    install_bins: src/bin/echam6
  6.3.04p1-esm-interface:
    branch: using_esm_interfaces
    destination: echam-6.3.04p1
    git-repository: https://gitlab.dkrz.de/modular_esm/echam6.git
  6.3.04p1-esm-interface-yac:
    branch: using_esm_interfaces_yac
    destination: echam-6.3.04p1
    git-repository: https://gitlab.dkrz.de/modular_esm/echam6.git
  6.3.04p1-paleodyn:
    branch: paleodyn
    destination: echam-6.3.04p1
    git-repository: https://gitlab.dkrz.de/modular_esm/echam6.git
  6.3.05p2:
    branch: esm-tools
    git-repository: https://gitlab.dkrz.de/foci/src/echam.git
  6.3.05p2-concurrent_radiation:
    branch: concurrent_radiation
    clean_command: rm -rf src/echam/bin; make clean
    comp_command: make -j `nproc --all`; make install -j `nproc --all`; mkdir -p src/echam/bin;
      cp  bin/echam6 src/echam/bin/echam6
    conf_command: export OASIS3MCT_FC_LIB=$(pwd)/../lib/; export OASIS3MCTROOT=$(pwd)/../oasis/;
      ./config/createMakefiles.pl; autoreconf -i --force; mkdir -p src/.deps yaxt/src/.deps
      yaxt/tests/.deps; ./configure --with-coupler=oasis3-mct --with-fortran=intel
      INSTALL='/usr/bin/install -p'
    git-repository: https://gitlab.dkrz.de/PalMod/echam6-PalMod.git
  6.3.05p2-foci:
    branch: esm-tools
    git-repository: https://git.geomar.de/foci/src/echam.git
  6.3.05p2-wiso:
    branch: wiso
    clean_command: make clean
    comp_command: make; make install
    conf_command: ./configure
clean_command: ${defaults.clean_command}
comp_command: ${defaults.comp_command}
git-repository: https://gitlab.dkrz.de/modular_esm/echam6.git
install_bins: src/echam/bin/echam6
# Minichange to trigger CI (PG: write randowm stuff here and commit it to trigger CI builds with ECHAM as a component)
