archfile: ESMTOOLS_generic_intel
available_versions:
- 2.0_r982_ogcm
- 2.0_r982
branch: esm-tools
choose_version:
  2.0_r982:
    archfile: ESMTOOLS_generic_oasis_intel
    nothing: much
    use_oasis: --use_oasis oasis3_mct
  2.0_r982_ogcm:
    archfile: ESMTOOLS_generic_intel
    use_oasis: ''
clean_command: rm -rf bin lib obj ppsrc
comp_command: if [[ $HOSTNAME =~ juwels ]] ; then module unload GCCcore; fi; export XIOS_TOPLEVEL=${model_dir}; ./make_xios --arch ${archfile} --netcdf_lib
  netcdf4_par --full ${use_oasis} --job 24; cp bin/xios_server.exe bin/xios.x
destination: xios-${version}
git-repository: https://git.geomar.de/foci/src/xios.git
install_bins: bin/xios.x
use_oasis: ''
