# JUWELS YAML CONFIGURATION FILE

computer:
    # basic setup
    name: juwels
    account: esmtst
    jobtype: compute
    accounting: true

    # default settings for compiler, mpi and I/O libs
    compiler_mpi: intel2025_psmpi
    iolibraries: system_libs

    # slurm setup
    batch_system: slurm
    logical_cpus_per_core: 2
    threads_per_core: 1
    launcher_flags: "-l "
    hetjob_flag: packjob

    # set default for hyperthreading_flag
    hyperthreading_flag: ""

    use_hyperthreading: False
    hetjob_strategy: taskset
    choose_use_hyperthreading:
            "1":
                    hyperthreading_flag: ""
            True:
                    hyperthreading_flag: ""
            "0":
                    choose_heterogeneous_parallelization:
                            False:
                                    hyperthreading_flag: "--ntasks-per-core=1"
                            True:
                                    hyperthreading_flag: ""
                                    add_unset_vars:
                                            - "SLURM_DISTRIBUTION"
                                            - "SLURM_NTASKS"
                                            - "SLURM_NPROCS"
                                            - "SLURM_ARBITRARY_NODELIST"
            False:
                    choose_heterogeneous_parallelization:
                            False:
                                    hyperthreading_flag: "--ntasks-per-core=1"
                            True:
                                    hyperthreading_flag: ""
                                    add_unset_vars:
                                            - "SLURM_DISTRIBUTION"
                                            - "SLURM_NTASKS"
                                            - "SLURM_NPROCS"
                                            - "SLURM_ARBITRARY_NODELIST"

    sh_interpreter: "/usr/bin/bash"

    # pool directories
    # TODO: cleanup the pool / focipool logic
    pool_dir:  "/pool/data/not/available/on/juwels"
    pool_directories:
            pool: "/pool/data/not/available/on/juwels"
            focipool: "/p/project/hirace/foci_input2"

    partition: batch

    choose_partition:
            batch:
                    partition_name: batch
                    partition_cpn: 48
            devel:
                    partition_name: devel
                    partition_cpn: 48

    partitions:
            compute:
                    name: ${computer.partition_name}
                    cores_per_node: ${computer.partition_cpn}
            pp:
                    name: ${computer.partition_name}
                    cores_per_node: ${computer.partition_cpn}

    # basic modules and export vars needed
    # for all compiler and I/O settings
    module_actions:
            - "use $OTHERSTAGES"

    export_vars:
            LC_ALL: en_US.UTF-8
            TMPDIR: /tmp

    # choose compiler and MPI implementation
    choose_compiler_mpi:

       intel2025_psmpi:
          add_module_actions:
            - "purge"
            - "load Stages/2025"
            - "load Intel/2024.2.0"
            - "load ParaStationMPI/5.10.0-1"
            - "load CMake/3.29.3"
            - "load Python/3.12.3"
            - "load imkl/2024.2.0"
            - "load Perl/5.38.2"
            - "load Perl-bundle-CPAN/5.38.2"
            - "load git/2.45.1"
          add_export_vars:
            FC: mpifort
            F77: mpifort
            MPIFC: mpifort
            FCFLAGS: -free
            CC: mpicc
            CXX: mpic++
            MPIROOT: "\"$($FC -show | perl -lne 'm{ -I(.*?)/include } and print $1')\""
            MPI_LIB: "\"$($FC -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')\""

       gnu2023_ompi2023:
          add_module_actions:
            - "load Stages/2023"
            - "load GCC/11.3.0"
            - "load OpenMPI/4.1.4"
            - "load CMake/3.26.3"
            - "load Python/3.10.4"
            - "load imkl/2022.1.0"
            - "load Perl/5.34.1"
            - "load git"
          add_export_vars:
            FC: mpifort
            F77: mpifort
            MPIFC: mpifort
            FCFLAGS: -free
            CC: mpicc
            CXX: mpic++
            MPIROOT: "\"$($FC -show | perl -lne 'm{ -I(.*?)/include } and print $1')\""
            MPI_LIB: "\"$($FC -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')\""

       gnu2024_ompi2024:
          add_module_actions:
            - "load Stages/2024"
            - "load GCC"
            - "load OpenMPI"
            - "load CMake"
            - "load Python"
            - "load imkl"
            - "load Perl"
            - "load git"
          add_export_vars:
            FC: mpifort
            F77: mpifort
            MPIFC: mpifort
            FCFLAGS: -free
            CC: mpicc
            CXX: mpic++
            MPIROOT: "\"$($FC -show | perl -lne 'm{ -I(.*?)/include } and print $1')\""
            MPI_LIB: "\"$($FC -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')\""

    choose_iolibraries:

        # DEFAULT LIBS
        system_libs:
           # TODO: find the correct libraries and dependencies
           add_module_actions:
             - "load libaec FFTW cURL netCDF netCDF-Fortran ecCodes CDO NCO"
             - "list"
           add_export_vars:
                AEC_ROOT: $EBROOTLIBAEC
                SZIPROOT: $EBROOTLIBAEC
                HDF5ROOT: $EBROOTHDF5
                HDF5_ROOT: $EBROOTHDF5
                NETCDFROOT: $EBROOTNETCDF
                NETCDFFROOT: $EBROOTNETCDFMINFORTRAN
                ECCODESROOT: $EBROOTECCODES

                HDF5_C_INCLUDE_DIRECTORIES: $HDF5_ROOT/include
                NETCDF_Fortran_INCLUDE_DIRECTORIES: $NETCDFFROOT/include
                NETCDF_C_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                NETCDF_CXX_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                OASIS3MCT_FC_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
                PERL5LIB: /p/project/chhb19/HPC_libraries/perl5/lib/perl5
                PERL5_PATH: $PERL5LIB
                PERL5OPT: '-Mwarnings=FATAL,uninitialized'
                MKL_CBWR: AUTO,STRICT
                LD_RUN_PATH: $LD_LIBRARY_PATH

        # AWI LIBS
        awi_libs:
            add_export_vars:
                PROJECT_ID: '$(for i in $(id -Gn $whoami);do echo "  - $i" ;done | grep chhb | head -1 | cut -c 5-10)'
                IO_LIB_ROOT: "<WILL_BE_OVERWERITTEN>"
                LD_LIBRARY_PATH: $IO_LIB_ROOT/lib:$LD_LIBRARY_PATH

                SZIPROOT: $IO_LIB_ROOT
                HDF5ROOT: $IO_LIB_ROOT
                HDF5_ROOT: $HDF5ROOT
                NETCDFROOT: $IO_LIB_ROOT
                NETCDFFROOT: $IO_LIB_ROOT
                ECCODESROOT: $IO_LIB_ROOT

                HDF5_C_INCLUDE_DIRECTORIES: $HDF5_ROOT/include
                NETCDF_Fortran_INCLUDE_DIRECTORIES: $NETCDFFROOT/include
                NETCDF_C_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                NETCDF_CXX_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                OASIS3MCT_FC_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
                PATH: $IO_LIB_ROOT/bin:$PATH

                # For OASIS3-MCT5 from CERFACS
                OASIS_NETCDF: $NETCDFROOT
                OASIS_NETCDFF: $NETCDFFROOT

        # GEOMAR LIBS
        geomar_libs:
            add_export_vars:
                IO_LIB_ROOT: "<WILL_BE_OVERWERITTEN>"
                PATH: $IO_LIB_ROOT/bin:$PATH
                LD_LIBRARY_PATH: $IO_LIB_ROOT/lib:$LD_LIBRARY_PATH

                SZIPROOT: $IO_LIB_ROOT
                HDF5ROOT: $IO_LIB_ROOT
                HDF5_ROOT: $HDF5ROOT
                NETCDFROOT: $IO_LIB_ROOT
                NETCDFFROOT: $IO_LIB_ROOT
                ECCODESROOT: $IO_LIB_ROOT

                # For OASIS3-MCT5 from CERFACS
                OASIS_NETCDF: $NETCDFROOT
                OASIS_NETCDFF: $NETCDFFROOT

                HDF5_C_INCLUDE_DIRECTORIES: $HDF5_ROOT/include
                NETCDF_Fortran_INCLUDE_DIRECTORIES: $NETCDFFROOT/include
                NETCDF_C_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                NETCDF_CXX_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                OASIS3MCT_FC_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'

    # some yamls use computer.fc, etc to identify the compiler, so we need to add them
    fc: "$FC"
    cc: "$CC"
    mpifc: "$MPIFC"
    mpicc: "$MPICC"
    cxx: "$CXX"

    further_reading:
            - batch_system/slurm.yaml

