components:
- xios-2.5.3
- rnfmap-v1.3
- oifs-48r1v4
- fesom-2.7.6
- oasis3mct-5.2
- lpj_guess-4.1.5
coupling_changes:
- sed -i 's/xios-2.5+/xios/g' oifs-48r1/bundle.yml
- sed -i 's/xios\/build_ecearth/xios/g' oifs-48r1/bundle.yml
- sed -i 's/oasis3-mct-5.2/oasis/g' oifs-48r1/bundle.yml
