definitions:
  atm2oce: &atm2oce
    src_component: atmo
    src_grid: icon_atmos_grid
    tgt_component: fesom2
    tgt_grid: fesom_grid
    time_reduction: average
    src_lag: 1
    tgt_lag: 1
  oce2atm: &oce2atm
    src_component: fesom2
    src_grid: fesom_grid
    tgt_component: atmo
    tgt_grid: icon_atmos_grid
    time_reduction: average
    src_lag: 1
    tgt_lag: 1
  interp_stacks:
    hcsbb_interp_stack: &hcsbb_interp_stack
      interpolation:
        - bernstein_bezier
        - nnn:
            n: 4
            weighted: arithmetic_average
        - fixed:
            user_value: -999.9
    conserv_interp_stack: &conserv_interp_stack
      interpolation:
        - conservative:
            order: 1
            enforced_conservation: false
            partial_coverage: true
            normalisation: fracarea
        - fixed:
            user_value: 0
    spmap_interp_stack: &spmap_interp_stack
      interpolation:
        - source_to_target_map

timestep_unit: ISO_format
calendar: proleptic-gregorian
coupling:
  - <<: [ *atm2oce, *hcsbb_interp_stack ]
    coupling_period: PT30M
    field:
      - src: surface_downward_eastward_stress
        tgt: taux
      - src: surface_downward_northward_stress
        tgt: tauy
#  - <<: [ *atm2oce, *hcsbb_interp_stack ]
#    coupling_period: PT30M
#    field: [10m_wind_speed]
  - <<: [ *atm2oce, *conserv_interp_stack ]
    coupling_period: PT30M
    field: [surface_fresh_water_flux,
            total_heat_flux,
            atmosphere_sea_ice_bundle]
  - <<: [ *oce2atm, *conserv_interp_stack ]
    coupling_period: PT30M
    field:
      - src: sst_feom
        tgt: sea_surface_temperature
      - ocean_sea_ice_bundle
#  - <<: [ *oce2atm, *conserv_interp_stack ]
#    coupling_period: PT30M
#    field: [eastward_sea_water_velocity,
#            northward_sea_water_velocity]
#  - <<: [ *atm2oce, *spmap_interp_stack ]
#    coupling_period: PT30M
#    field: river_runoff
