model: yac

available_versions:
- 1.5.5
clean_command: make clean
comp_command: make
conf_command: autoreconf -iv; ./configure LDFLAGS=-Wl,-rpath,$NETCDFROOT/lib --with-xml2-include=/usr/include/libxml2
  --with-xml2-lib=/usr/lib64/ --with-netcdf-root=$NETCDFROOT --with-clapack-root=${model_dir}/clapack
  --disable-lib-only --enable-silent-rules
destination: yac
choose_version:
        1.5.5:
                branch: v1.5.5
                repo_tag: v1.5.5
git-repository: https://gitlab.dkrz.de/dkrz-sw/yac.git

metadata:
    Information: "For more information about YAC please go to the webpage: https://dkrz-sw.gitlab-pages.dkrz.de/yac/index.html"


config_files:
    coupling_xsd:  coupling_xsd
