#########################################################################################
######################### FESOM-RECOM YAML CONFIGURATION FILE ###########################
#########################################################################################

general:
        model: fesom-recom
        #model_dir: ${esm_master_dir}/fesom-recom-${version}

        version: "1.4"

        coupled_setup: False
        standalone: True

        include_models:
                - recom
                - fesom

        available_versions:
        - '1.4'
        - '2.0'
        choose_version:
          '1.4':
            couplings:
            - fesom-1.4+recom-2.0

        choose_computer.name:
                blogin:
                        add_runtime_environment_changes:
                                add_add_export_vars:
                                        # MA: Delete in the future, when libraries in blogin.yaml
                                        # do the job for fesom-recom-1.4 as well (talk about this
                                        # with Sebastian)
                                        - "IO_LIB_ROOT=/sw/dataformats/netcdf/intel.18/4.7.3/skl/"
                                        - "LD_LIBRARY_PATH=$IO_LIB_ROOT/lib:$LD_LIBRARY_PATH"
                                        - "ZLIBROOT=$IO_LIB_ROOT"
                                        - "SZIPROOT=$IO_LIB_ROOT"
                                        - "HDF5ROOT=$IO_LIB_ROOT"
                                        - "HDF5_ROOT=$HDF5ROOT"
                                        - "NETCDFROOT=$IO_LIB_ROOT"
                                        - "NETCDFFROOT=$IO_LIB_ROOT"
                                        - "HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include"
                                        - "NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include"
                                        - "NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/netcdf-cxx4-4.3.1/cxx4/"
                                        - 'OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"'


#########################################################################################
########### necessary changes to submodels compared to standalone setups ################
#########################################################################################

fesom:
        version: "1.4-recom"
        model_dir: "${general.model_dir}/fesom-${fesom.version}/"
        setup_dir: "${general.model_dir}"

        time_step: 900
        output_unit: "${restart_unit}"
        leapyear: false

        opbnd_dir: ""
        tide_forcing_dir: ""

        asforcing: CORE2
        asforcing_wind_rad_precip: JRA55

        namelist_changes:   # Change to add_namelist_changes when the bug is fixed
                namelist.config:
                        inout:
                                levelwise_output: true
                                output_length_unit: "${output_unit}"
                                output_length_unit_restart: "${restart_unit}"
                        #mesh_def:
                                #part_format: 0  #this option is required because of two ways
                                                #of storring mapping arrays are currently in use
                                                #option with part_format=0 shall be used in future!
                namelist.diag:
                        diag_flag:
                                diag_oce_KE: "remove_from_namelist"
                                diag_oce_energy_conv: "remove_from_namelist"
                                diag_oce_Kv: "remove_from_namelist"
                                diag_mesh: "remove_from_namelist"
                namelist.forcing:
                        forcing_source:
                                wind_data_source: "${asforcing_wind_rad_precip}"
                                rad_data_source: "${asforcing_wind_rad_precip}"
                                precip_data_source: "${asforcing_wind_rad_precip}"
                                wind_ttp_ind: 5
                                rad_ttp_ind: 5
                                precip_ttp_ind: 5
                                runoff_ttp_ind: 3
                        forcing_reso:
                                forcing_grid: 'T319'    #'T62','T319', 'other'
                        forcing_bulk:
                                AOMIP_drag_coeff: true
                namelist.oce:
                        viscdiff:
                                Kh0: 800.0 # default for setup with recom involved

        choose_lresume:
                true:
                        choose_general.run_number:
                                1:      # Restart from runscript
                                        age_tracer_sy: "${first_initial_year}"
                                        first_initial_year: "${general.first_initial_year}"
                                        ini_parent_exp_id: "${general.ini_parent_exp_id}"
                                        ini_restart_dir: "${general.ini_restart_dir}/fesom/"
                                        ini_parent_date: "${prev_date}"

                                "*":
                                        age_tracer_sy: "${general.initial_date!syear}"
                false:
                        age_tracer_sy: "${general.initial_date!syear}"


#########################################################################################

recom:
        version: "2.0"
        model_dir: "${general.model_dir}/recom/"
        setup_dir: "${general.model_dir}"

        time_step: "${fesom.time_step}"

        choose_lresume:
                true:
                        choose_general.run_number:
                                1:      # Restart from runscript
                                        ini_parent_exp_id: "${general.ini_parent_exp_id}"
                                        ini_restart_dir: "${general.ini_restart_dir}/recom/"
                                        ini_parent_date: "${prev_date}"
