components:
- echam-6.3.04p1-paleodyn
- fesom-2.0-paleodyn
- oasis3mct-2.8-paleodyn
- pism-github1.2
- scope-dev
coupling_changes:
- sed -i '/set(FESOM_COUPLED/s/OFF/ON/g' fesom-2.0/CMakeLists.txt
- sed -i '/ECHAM6_COUPLED/s/OFF/ON/g' echam-6.3.04p1/CMakeLists.txt
