# MPIOM YAML CONFIGURATION FILE
#

model: mpiom

available_versions:
- 1.6.2p3
- 1.6.3
- 1.6.3p2
choose_version:
  1.6.2p3:
    branch: 1.6.2p3
  1.6.3:
    branch: 1.6.3
  1.6.3p2:
    branch: 1.6.3p2
install_bins: bin/mpiom.x
clean_command: make clean
comp_command: make -j `nproc --all`
conf_command: ./configure --prefix=${model_dir} --disable-mh-file --enable-HAMOCC --with-mpi=intelmpi
git-repository: https://gitlab.dkrz.de/modular_esm/mpiom.git
contact: "miguel.andres-martinez(at)awi.de, paul.gierz(at)awi.de"

metadata:
        Institute: MPI-Met
        Description:
                The ocean-sea ice component of the MPI-ESM. MPIOM is a primitive equation
                model (C-Grid, z-coordinates, free surface) with the hydrostatic and
                Boussinesq assumptions made.
        Authors: Till Maier-Reimer, Helmuth Haak, Johann Jungclaus
        Publications:
                - "Characteristics of the ocean simulations in the Max Planck Institute Ocean Model (MPIOM) the ocean component of the MPI-Earth system model <https://doi.org/10.1002/jame.20023>"
                - "The Max-Planck-Institute global ocean/sea ice model with orthogonal curvilinear coordinates <https://doi.org/10.1016/S1463-5003(02)00015-X>"
        License:
                Please make sure you have a licence to use MPIOM. In case you are unsure,
                please contact redmine...

executable: mpiom

setup_dir: "${model_dir}"

time_step: 2700
resolution: GR15

further_reading:
        - mpiom/mpiom.compiletime_env_changes.yaml

