#########################################################################################
######################### NAME_VERSION YAML CONFIGURATION FILE ##########################
#########################################################################################
computer:
    choose_computer.name:
        levante:
            #compiler_mpi: gnu11_ompi4
            compiler_mpi: intel2022_openmpi
            iolibraries: system_libs
general:
    model: icon-fesom 
    version: "v1.0"
    coupled_setup: True

    include_models: # List of models, couplers and componentes of the setup.
    - icon 
    - fesom 
    - yac
    choose_version:
        v1.0:
            couplings:
            - fesom-2.6.x-yac-sl+icon-2025.04-public-sl
        v2.0:
            couplings:
            # seb-wahls dirty workaroud: we use 2.7.7 but as we rely on the fesom-2.6.yaml we 
            # need to keep 2.6 in th coupling name until I have a correct fesom-2.7.yaml
            # see esm_parster around line 158 (def look_for_file)
            # and fesom-2.6.yaml
            - fesom-2.6.2-yac+icon-2025.10-public

    prepcompute_recipe:
        - "compile_model"
        - "_show_simulation_info"
        - "create_new_files"
        - "create_empty_folders"
        # no need to prepare coupler files with yac
        # - "prepare_coupler_files"
        - "assemble"
        - "log_used_files"
        - "wait_for_iterative_coupling"
        - "copy_files_to_thisrun"
        - "modify_namelists"
        - "modify_files"
        - "copy_files_to_work"
        - "report_missing_files"
        - "compute_and_log_file_checksums"
        - "_write_finalized_config"
        - "database_entry"

fesom:
    choose_general.version:
       v1.0:
           model_dir: ${general.model_dir}/fesom-2.6
       v2.0:
           model_dir: ${general.model_dir}/fesom-2.7

    file_movements:
      input:
         all_directions: link
      forcing:
         all_directions: link
      outdata:
         all_directions: move
      unknown:
         all_directions: move

yac:
    input_sources:
        coupling_yaml: ${computer.pool_directories.focipool}/ICON-FESOM/YAC/coupling.yaml
    input_files:
        coupling_yaml: coupling_yaml 
    input_in_work:
        coupling_yaml: coupling.yaml 
