#########################################################################################
######################### MPIESM YAML CONFIGURATION FILE ################################
#########################################################################################

general:
        model: mpiesm
        #model_dir: ${esm_master_dir}/mpiesm-${version}

        coupled_setup: True

        include_models:
                - echam
                - mpiom
                - oasis3mct

        version: "1.2"
        resolution: ${echam.resolution}_${mpiom.resolution}
        post_time: "00:60:00"
        choose_general.resolution:
                T31_GR30:
                        compute_time: "00:60:00"
                T63_GR15:
                        compute_time: "00:60:00"

        postprocessing: -1 #V19?, what does it mean -1?

        #choose_lresume:
        #        true:
        #                echam:
        #                        pseudo_resume_date: $(( ${echam.start_date} - ${echam.time_step}))
        #                        pseudo_end_date: $(( ${echam.next_date} - ${echam.time_step}))

        #forcing_sources:
        #        lctlib: "${model_dir}/util/running/adjunct_files/jsbach/lctlib_nlct21.def"

        available_versions:
        - 1.2.00p4
        - 1.2.01
        - 1.2.01p1
        choose_version:
          1.2.00p4:
            couplings:
            - mpiom-1.6.2p3+echam-6.3.02p4
          1.2.01:
            couplings:
            - mpiom-1.6.3+echam-6.3.04p1
          1.2.01p1:
            couplings:
            - mpiom-1.6.3p2+echam-6.3.05p2


#########################################################################################

echam:
        timestep: 400
        choose_computer.cores_per_node:
                24:
                        choose_general.resolution:
                                T31_GR30:
                                        nnodes: 18
                                        nproca: 24
                                        nprocb: 18
                                T63_GR15:
                                        nnodes: 24
                                        nproca: 24
                                        nprocb: 24
                36:
                        choose_general.resolution:
                                T31_GR30:
                                        nnodes: 12
                                        nproca: 24
                                        nprocb: 18
                                T63_GR15:
                                        nnodes: 12
                                        nproca: 18
                                        nprocb: 20

#########################################################################################

mpiom:
        conf_command: ./configure --prefix=${model_dir} --disable-mh-file --with-coupler=oasis3-mct
          --enable-HAMOCC --with-mpi=intelmpi

        timestep: 2700
        choose_computer.cores_per_node:
                24:
                        choose_general.resolution:
                                T31_GR30:
                                        nnodes: 9
                                        nproca: 18
                                        nprocb: 12
                                T63_GR15:
                                        nnodes: 16
                                        nproca: 16
                                        nprocb: 24
                36:
                        choose_general.resolution:
                                T31_GR30:
                                        nnodes: 6
                                        nproca: 18
                                        nprocb: 12
                                T63_GR15:
                                        nnodes: 6
                                        nproca: 18
                                        nprocb: 12

#########################################################################################

oasis3mct:

        model_dir: ${general.model_dir}/oasis

        process_ordering: #V1?
                - mpiom
                - echam

        a2o_lag: "${echam.time_step}" #V4?
        o2a_lag: "${mpiom.time_step}" #V2?
        a2o_seq: 1 #V3?
        o2a_seq: 1 #V3?

        coupling_time_step: 86400 #V17
        #coupling_target_fields:
        #        o2a_flux: #V5
        #                - 'SSTATMOS <--conserv-- SSTOCEAN' #V7? conserv scalar?
        #                - 'SITATMOS <--conserv-- SITOCEAN'
        #                - 'SICATMOS <--conserv-- SICOCEAN'
        #                - 'SNTATMOS <--conserv-- SNTOCEAN'
        #                - 'OCUATMOS <--conserv-- OCUOCEAN' #V6? V8? conserv vector?
        #                - 'OCVATMOS <--conserv-- OCVOCEAN' #V6?
        #                - 'CO2TRAAT <--conserv-- CO2TRAOC' #V9? conserv scalar?
        #                - 'CO2ATMOS <--conserv-- CO2OCEAN'
        #        a2o_flux: #V10
        #                - 'FRIOCEAN <--conserv-- FRIATMOS' #V11? conserv scalar?
        #                - 'FRWOCEAN <--conserv-- FRWATMOS'
        #                - 'TXWOCEAS <--bicubic-- TXWATMOU' #V12? V13
        #                - 'TYWOCEAS <--bicubic-- TYWATMOU'
        #                - 'TXIOCEAS <--bicubic-- TXIATMOU'
        #                - 'TYIOCEAS <--bicubic-- TYIATMOU'
        #                - 'RHIOCEAN <--conserv-- RHIATMOS' #V14? V15? conserv scalar?
        #                - 'CHIOCEAN <--conserv-- CHIATMOS'
        #                - 'NHWOCEAN <--conserv-- NHWATMOS'
        #                - 'SHWOCEAN <--conserv-- SHWATMOS'
        #                - 'WSVOCEAN <--conserv-- WSVATMOS'
        #                - 'CO2CONOC <--conserv-- CO2CONAT'
        #                - 'CO2FLXOC <--conserv-- CO2FLXAT' #V16? V15?

        coupling_directions:
                'mpiom->atmo':
                        lag: ${o2a_lag}
                        seq: ${o2a_seq}
                'atmo->mpiom':
                        lag: ${a2o_lag}
                        seq: ${a2o_seq}

        coupling_methods:
                conserv:
                        time_transformation: average #?
                        remapping:
                                - conserv:
                                        search_bin: latitude #V7
                                        nb_of_search_bins: 40 #V7
                                        normalization: fracarea #V7?
                                        order: first #V7
                                - mapping:
                                        mapname: rmp_oces_to_atmo_CONSERV_FRACAREA_${general.resolution}.nc #V19?
                                        map_regrid_on: src #V19?
                conserv2:
                        time_transformation: instant
                        remapping:
                                - conserv:
                                        search_bin: latitude
                                        nb_of_search_bins: 40
                                        normalization: fracnnei
                                        order: first
                                - mapping:
                                        mapname: rmp_atmo_to_opac_CONSERV_FRACNNEI_T63_ORCA05.nc
                                        map_regrid_on: src
                conserv3:
                        time_transformation: instant
                        remapping:
                                - conserv:
                                        search_bin: latitude
                                        nb_of_search_bins: 40
                                        normalization: fracnnei
                                        order: first
                                - mapping:
                                        mapname: rmp_atmo_to_opac_CONSERV_FRACNNEI_T63_ORCA05.nc
                                        map_regrid_on: src
                        postprocessing:
                                conserv:
                                        method: glbpos
                conserv4:
                        time_transformation: instant
                        remapping:
                                - conserv:
                                        search_bin: latitude
                                        nb_of_search_bins: 40
                                        normalization: fracnnei
                                        order: first
                                - mapping:
                                        mapname: rmp_atmo_to_opac_CONSERV_FRACNNEI_T63_ORCA05.nc
                                        map_regrid_on: src
                        postprocessing:
                                conserv:
                                        method: global
                bicubic:
                        time_transformation: instant #?
                        remapping:
                                - bicubic:
                                        search_bin: latitude #V13
                                        nb_of_search_bins: 40 #V13
                                - mapping:
                                        mapname: rmp_atmo_to_oces_BICUBIC_D_${general.resolution}.nc #V18?
                                        map_regrid_on: dst #V18?

