oifs:
    add_namelist_changes:
        fort.4:
            NAERAD:
                LAER3D: False
                NRADFR: -3
                NDECOLAT: 0
            NAMGWWMS:
                GGAUSSB: -0.5
    choose_resolution:
        '*':
            add_add_namelist_changes:
                fort.4:
                    NAMCLDP:
                        RVICE: 0.16
