choose_mip:
        "cmip5":
                add_namelist_changes:
                        fort.4:
                                NAERAD:
                                        CMIP5DATADIR: "${cmip5_data_dir_nml}"
        "cmip6":
                add_namelist_changes:
                        fort.4:
                                NAERAD:
                                        LCMIP6: ".true."
                                        CMIP6DATADIR: "${cmip6_data_dir_nml}"
                choose_scenario:
                        "piControl":
                                add_namelist_changes:
                                        fort.4:
                                                NAERAD:
                                                        NCMIPFIXYR: 1850
                        "SSP5-8.5":
                                add_namelist_changes:
                                        fort.4:
                                                NAERAD:
                                                        SSPNAME: "SSP5-8.5"
