lresume: ${echam.lresume}
time_step: ${echam.time_step}
#ini_parent_exp_id: ${echam.ini_parent_exp_id}
parent_date: ${echam.parent_date}
prev_date: ${echam.prev_date}
ini_restart_dir: ${echam.parent_restart_dir}/../hdmodel/
ini_parent_exp_id: ${echam.parent_expid}
