# ECHAM YAML DEFAULT CONFIGURATION FILE

model: hdmodel
repository: https://gitlab.dkrz.de/modular_esm/echam6
domain: hydrology

description: |
        The Hagemann/Duemenil hydrology model,
        (someone from Hamburg)
        paper citation

license_text: |
        Please make sure you have a licence to use echam. In case you are
        unsure, please contact redmine....

pool_dir: "${computer.pool_directories.pool}/JSBACH/input/${jsbach.dataset}/HD"
input_dir: "${pool_dir}"

executable: NONE

choose_lresume:
        False:
                input_files:
                        hdstart: hdstart
        True:
                restart_in_files:
                        hdrestart: hdrestart

                        #ini_restart_dir: "${pool_dir}/MPIESM/restart/dev/${parent_exp_id}/restart/jsbach"

#input_files :
#        hdpara: hdpara
#        rmp_hd: rmp_hd

input_in_work:
        #hdpara: "hdpara.nc"
        rmp_hd: "rmp_hd.nc"
        #hdstart: "hdstart.nc"

input_sources:
        hdpara: "${input_dir}/hdpara.nc"
        rmp_hd: "${input_dir}/rmp_${echam.resolution}_to_hd.nc"
        hdstart: "${input_dir}/hdstart.nc"


restart_in_in_work:
        hdrestart: hdrestart.nc

restart_in_sources:
        hdrestart: "${parent_restart_dir}/hdrestart.nc"


restart_out_in_work:
        hdrestart: hdrestart.nc

restart_out_sources:
        hdrestart: "${parent_restart_dir}/hdrestart.nc"

log_in_work:
        outflow: hd_outflow_*.log # DIBA muss noch rausfinden was * in diesem Fall ist


choose_hdpara_file:
        "*":
                input_sources:
                        hdpara: ${hdpara_file}


further_reading:
        - hdmodel/hdmodel.inherit.yaml
