# ESM-Runscripts defaults

# Defaults added to the general section
general:
    additional_files: []
    iterative_coupled_model: ""
    reset_calendar_to_last: False
    verbose: False

# Defaults to be added to each model or component
per_model_defaults:
        file_movements:
                default:
                        all_directions: copy
                bin:
                        init_to_exp:    copy
                        exp_to_run:     copy
                        run_to_work:    copy
                        work_to_run:    copy

# Default workflows if not specified by users
flows: 
        workflow:
                next_run_triggered_by: tidy
                subjobs:
                        postprocessing:
                                batch_or_shell: batch
                                order_in_cluster: concurrent
                                run_on_queue: ${computer.partitions.pp.name}
                                run_after: tidy
                                script_dir: </path/to/the/directory/containing/your/script/>
                                submit_to_batch_system: True
                                script: "<name_of_your_script>.sh/.py <whatever input variables you want to give>"
                                # for the python script use this: ${general.experiment_config_dir}/${general.expid}_finished_config.yaml_${run_datestamp}
                                nproc: 1
