# ESM-Runscripts defaults

# Defaults added to the general section
general:
    additional_files: []
    iterative_coupled_model: ""
    reset_calendar_to_last: False
    verbose: False
    profile: False
    intermediate_file_movements:
    - "config"
    - "bin"
    - "input"
    compute_file_checksums: False
    parallel_file_movements: "dask"
    force_overwrite_in_file_movements: False

# Defaults to be added to each model or component
per_model_defaults:
        file_movements:
                default:
                        all_directions: copy
                bin:
                        init_to_exp:    copy
                        exp_to_run:     copy
                        run_to_work:    copy
                        work_to_run:    copy

dask:
    scheduler_json_name: "dask_scheduler.json"
    scheduler_json: "${general.thisrun_work_dir}/${scheduler_json_name}"
    ignore_files:
        scheduler_json: scheduler_json
    ignore_in_work:
        scheduler_json: "${scheduler_json_name}"
