#per_model_defaults:
#        file_movements:
#                default:
#                        all_directions: copy
#                bin:
#                        init_to_exp:    copy
#                        exp_to_run:     copy
#                        run_to_work:    copy
#                        work_to_run:    copy
#                        
# GEOMAR defaults
per_model_defaults:
   file_movements:
      default:
         all_directions: copy
      log:
         all_directions: copy
      bin:
         init_to_exp: link
         exp_to_run: link
         run_to_work: link
         work_to_run: link
         #all_directions: link
      forcing:
         all_directions: link
      input:
         all_directions: link
      restart_in:
         all_directions: link
      restart_out:
         all_directions: copy
      config:
         init_to_exp: copy
         exp_to_run: link
         run_to_work: link
         work_to_run: link

