# Default recipies
# ESM-Tools uses config/esm_software/esm_runscripts/esm_plugins.yaml to understand
# where to look for each of this function/methods (the steps within each recipy, e.g.
# "_read_date_file").

choose_job_type:

        #postprocess:
        #        recipe:
        #                - "postprocess"

        prepare:
                recipe:
                        - "_read_date_file"
                        - "_update_run_in_chunk"
                        - "check_model_lresume"
                        # This must be done before resolve_some_choose_blocks, because
                        # potentially also choosable entries can be overridden via
                        # usermods.yaml (e.g. computer.useMPI: intel18_bullxmpi)
                        - "apply_last_minute_changes"
                        - "find_openmp"
                        - "resolve_some_choose_blocks"
                        - "_initialize_calendar"
                        - "set_chunk_calendar"
                        - "resolve_some_choose_blocks"
                        - "_add_all_folders"
                        - "set_prev_date"
                        - "set_parent_info"
                        - "finalize_config"
                        - "install_missing_plugins"
                        - "assemble_workflow"
                        - "restore_protected_last_minute_changes"
                        - "add_submission_info"
                        - "initialize_batch_system"
                        - "initialize_coupler"
                        - "set_logfile"
                        - "check_config_for_warnings_errors"

        assemble:
                recipe:
                        - "assemble"

        prepexp:
                recipe:
                        - "venv_bootstrap"
                        - "_create_setup_folders"
                        - "_create_component_folders"
                        - "initialize_experiment_logfile"
                        - "copy_tools_to_thisrun"
                        # The next step will call esm_runscripts again from the experiment folder,
                        # if the current folder is not the experiment folder already.
                        # If esm_runscripts will be excuted, the following step will be skipped, since
                        # there is a sys.exit() after the esm_runscripts call.
                        - "call_esm_runscripts_from_prepexp"
                        # The following step will be skipped, if not in experiment folder.
                        # It will only be called if esm_runscripts is called from experiment folder.
                        - "_copy_preliminary_files_from_experiment_to_thisrun"

        observe:
                recipe:
                        - "init_monitor_file"
                        - "wait_and_observe"
                        - "wake_up_call"

        tidy:
                recipe:
                        - "tidy_coupler"
                        - "assemble"
                        - "check_for_unknown_files"
                        - "log_used_files"
                        - "throw_away_some_infiles"
                        - "copy_stuff_back_from_work"
                        - "copy_all_results_to_exp"
                        - "clean_run_dir"

        prepcompute:
                recipe:
                        - "compile_model"
                        - "_show_simulation_info"
                        - "create_new_files"
                        - "create_empty_folders"
                        - "prepare_coupler_files"
                        - "assemble"
                        - "log_used_files"
                        - "wait_for_iterative_coupling"
                        - "copy_files_to_thisrun"
                        - "modify_namelists"
                        - "modify_files"
                        - "copy_files_to_work"
                        - "report_missing_files"
                        - "compute_and_log_file_checksums"
                        #- "add_vcs_info"
                        #- "check_vcs_info_against_last_run"
                        - "_write_finalized_config"
                        - "database_entry"

        inspect:
                recipe:
                        - "assemble"
                        - "inspect_workflow"
                        - "inspect_overview"
                        - "inspect_namelists"
                        - "inspect_size"
                        - "inspect_config"
                        - "inspect_folder"
                        - "inspect_file"

