#!/usr/bin/bash
#SBATCH --partition=mpp
#SBATCH --time=00:15:00
#SBATCH --ntasks=864
#SBATCH --output=/work/ollie/mandresm/testing//run/awicm//awicm2-initial-monthly/log/awicm2-initial-monthly_awicm_compute_20000101-20000131.log --error=/work/ollie/mandresm/testing//run/awicm//awicm2-initial-monthly/log/awicm2-initial-monthly_awicm_compute_20000101-20000131.log
#SBATCH --job-name=awicm2-initial-monthly
#SBATCH --mail-type=NONE
#SBATCH --exclusive

module purge
module load cmake
module load udunits
module load gribapi/1.28.0
module unload intel.compiler
module load intel.compiler
module unload netcdf
module load hdf5
module load centoslibs cdo nco netcdf/4.6.2_intel
module load automake
module load python3/3.7.7_intel2020u2
module load git
module list
module unload intel.mpi
module load intel.mpi

export LC_ALL=en_US.UTF-8
export FC="mpiifort -mkl"
export F77="mpiifort -mkl"
export MPIFC=mpiifort
export MPICC=mpiicc
export CC=mpiicc
export CXX=mpiicpc
export HDF5ROOT=$HDF5_ROOT
export NETCDFFROOT=$NETCDF_DIR
export NETCDFROOT=$NETCDF_DIR
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_LIBRARIES=$NETCDFROOT/lib
export PERL5LIB=/usr/lib64/perl5
export LAPACK_LIB="-lmkl_intel_lp64 -lmkl_core -mkl=sequential -lpthread -lm -ldl"
export LAPACK_LIB_DEFAULT="-L/global/AWIsoft/intel/2018/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential"
export XML2ROOT=/usr
export ZLIBROOT=/usr
export MPIROOT=${I_MPI_ROOT}/intel64
export MPI_LIB=$(mpiifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')
export PATH=/work/ollie/jhegewal/sw/cmake/bin:$PATH
export takenfrom=fesom2_run
export taken2from=fesom2_ru
export ACCOUNT=None
export ESM_TESTING_DIR=/work/ollie/mandresm/testing//run/awicm/
export MODEL_DIR=/work/ollie/mandresm/testing//comp/awicm/awicm-2.0
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!

echo $(date +"%a %b  %e %T %Y") : compute 1 2000-01-01T00:00:00 120652 - start >> /work/ollie/mandresm/testing//run/awicm//awicm2-initial-monthly/log//awicm2-initial-monthly_awicm.log

cd /work/ollie/mandresm/testing//run/awicm//awicm2-initial-monthly/run_20000101-20000131/work/
time srun -l --kill-on-bad-exit=1 --cpu_bind=cores --multi-prog hostfile_srun 2>&1 &

# Call to esm_runscript to start subjobs:
# ['tidy']
process=$! 
# Comment the following line if you don't want esm_runscripts to restart:
cd /work/ollie/mandresm/testing//run/awicm//awicm2-initial-monthly/scripts/
esm_runscripts awicm2-initial-monthly.yaml -e awicm2-initial-monthly -t observe_compute -p ${process} -s 20000101 -r 1 -v  --open-run

echo $(date +"%a %b  %e %T %Y") : compute 1 2000-01-01T00:00:00 120652 - done >> /work/ollie/mandresm/testing//run/awicm//awicm2-initial-monthly/log//awicm2-initial-monthly_awicm.log

wait
