# LPJ-GUESS 4
#
# For more information about the extended YAML syntax, please consult:
# https://esm-tools.readthedocs.io/en/latest/yaml.html#esm-tools-extended-yaml-syntax
#
# For more information about the ESM-Tools feature variables available, please consult:
# https://esm-tools.readthedocs.io/en/latest/esm_variables.html#esm-tools-variables

further_reading:
    - configs/components/lpj_guess/lpj_guess.cmip.yaml

lpj_guess:
    model: lpj_guess
    version: 4.1.2

    metadata:
        Institute: Lund Universitiy
        Description: Dynamic vegetation model
        Authors: Ben Smith
        Publications:
            - "Smith, B., Prentice, I.C. & Sykes, M.T. 2001. Representation of vegetation dynamics in the modelling of terrestrial ecosystems: comparing two contrasting approaches within European climate space. Global Ecology & Biogeography 10: 621-637. <https://doi.org/10.1046/j.1466-822X.2001.t01-1-00256.x>"
            - "Sitch, S., Smith, B., Prentice, I.C., Arneth, A., Bondeau, A., Cramer, W., Kaplan, J., Levis, S., Lucht, W., Sykes, M., Thonicke, K. & Venevsky, S. 2003. Evaluation of ecosystem dynamics, plant geography and terrestrial carbon cycling in the LPJ Dynamic Global Vegetation Model. Global Change Biology 9: 161-185. <https://doi.org/10.1046/j.1365-2486.2003.00569.x>"
            - "Martín Belda, D., Anthoni, P., Wårlind, D., Olin, S., Schurgers, G., Tang, J., Smith, B., & Arneth, A. 2022. LPJ-GUESS/LSMv1.0: A next generation Land Surface Model with high ecological realism. Geoscientific Model Development: <https://doi.org/10.5194/gmd-15-6709-2022>"
            - "Nord, J., Anthoni, P., Gregor, K., Gustafson, A., Hantson, S., Lindeskog, M., Meyer, B., Miller, P., Nieradzik, L., Olin, S., Papastefanou, P., Smith, B., Tang, J., Wårlind, D., & and past LPJ-GUESS contributors. (2021). LPJ-GUESS Release v4.1.1 model code (4.1.1). Zenodo. <https://doi.org/10.5281/zenodo.8065737>"
        License: Mozilla Public License Version 2.0


    git-repository: https://gitlab.dkrz.de/ec-earth/lpj-guess4.1.1.git
    destination: lpj_guess
    branch: main
    #comp_command: "mkdir -p ${model_dir}/build; cd ${model_dir}/build; cmake ..; make -j8"
    comp_command: "mkdir -p build; cd build; cmake ..; make -j8"

    setup_dir: "${model_dir}"
    bin_dir: "${setup_dir}/bin"
    install_bins: "build/guess"
    clean_command: "rm -rf build"
    executable: guess_TL255
    execution_command: ${executable} ${runscript_name}
    #resolution: TL159 #if it's not set i dosen't work!
    resolution: TL255 #if it's not set i dosen't work!
    TM5: 0

    choose_version:
        4.1.1:
            runscript_name: run_trunk_4_1.ins
            git-repository: https://gitlab.dkrz.de/ec-earth/lpj-guess4.1.1.git
            branch: main
        4.1.2:
            runscript_name: run_coupled_4_1_2.ins
            git-repository: https://git.smhi.se/e8891/lpjg-4.1.git
            branch: lpj_guess_awiesm3
            mygrid: TCO319
            install_bins: build/guess
            executable: guess


    # Automatically select the source code for esm_master if the command is operating
    # with a coupled setup
    model_dir: ${general.model_dir}

    choose_computer.name:
        levante:
            pool_dir: "/work/pd1284/AWIESM"

    # Some recommended defaults (restart for old experiment yes or no?)
    lresume: false
    time_step: 86400

    choose_lresume:
        false:
            restart_num: 0
        true:
            restart_num: 1

    # Some commonly used variables in other ESM-Tools components (but optional)
    input_dir: ${pool_dir}/lpj-guess/

    # CMIP N deposition directory (empty string to disable, otherwise full path with trailing /)
    ndep_input_dir: ${input_dir}/ndep/${resolution}/

    # Define files to ignore
    ignore_files:
        outputs: outputs
        log: log
    ignore_in_work:
        # Ignore output files with the same name
        outputs: "output/*.out"
        # Ignore log files
        log: "*.log"
    ignore_sources:
        outputs: "output/*.out"
        log: "*.log"

    namelist_dir: ${general.esm_namelist_dir}/lpj_guess/
    gridlist_dir: ${input_dir}/gridlists/
    forcing_dir: ${input_dir}/climate_forcing_data/

    #gridlist: "full_global" # sets up grid cell list =/ setup_name!!
    gridlist: "home" # sets up grid cell list =/ setup_name!!
    setup_name: global # sets up all the model parameters


    # File dictionaries
    config_sources:
        runscript: ${namelist_dir}/run_trunk_4_1.j2
        forcing_path_file: ${namelist_dir}/paths_forcing.j2
    config_in_work:
        runscript: ${runscript_name}
        forcing_path_file: paths_forcing.ins

    bin_sources:
        bin_tag: ${model_dir}/bin/${executable}

    lpjg_parent_state: $((${parent_date!syear}+1))
    lpjg_end_state: $((${end_date!syear}+1))

    restart_in_files:
        state: state
    restart_in_in_work:
        state: lpjg_state_${lpjg_parent_state}/*
    restart_in_sources:
        state: lpjg_state_${lpjg_parent_state}/*
    restart_out_files:
        state: state
    restart_out_in_work:
        state: lpjg_state_${lpjg_end_state}/*
    restart_out_sources:
        state: lpjg_state_${lpjg_end_state}/*

    # Soil type file
    slt_dir: ${input_dir}/slt/

    # N deposition forcing files - link from input to work/ndep with renamed filenames
    forcing_files:
        slt: slt
        drynhx: drynhx
        drynoy: drynoy
        wetnhx: wetnhx
        wetnoy: wetnoy
    forcing_sources:
        slt: ${slt_dir}/slt_${resolution}.nc
        drynhx: ${ndep_input_dir}/drynhx_${resolution}_hist_d1.nc
        drynoy: ${ndep_input_dir}/drynoy_${resolution}_hist_d1.nc
        wetnhx: ${ndep_input_dir}/wetnhx_${resolution}_hist_d1.nc
        wetnoy: ${ndep_input_dir}/wetnoy_${resolution}_hist_d1.nc
    forcing_in_work:
        slt: slt_${resolution}.nc
        drynhx: ndep/drynhx2.nc
        drynoy: ndep/drynoy2.nc
        wetnhx: ndep/wetnhx2.nc
        wetnoy: ndep/wetnoy2.nc

    choose_resolution:
        # Note:
        # Tco grids only work with version 43r3.
        TCO95:
            nx: 40320
            ny: 1
            oasis_grid_name: "096"
            res_number: 95
            res_number_tl: "95_4"
            truncation: "TCO"
        TL159:
            nx: 35718
            ny: 1
            oasis_grid_name: "080"
            res_number: 159
            res_number_tl: "159l_2"
            truncation: "TL"
        TCO159:
            nx: 108160
            ny: 1
            oasis_grid_name: "160"
            res_number: 159
            res_number_tl: "159_4"
            truncation: "TCO"
        TCO199:
            nx: 167200
            ny: 1
            oasis_grid_name: "200"
            res_number: 199
            res_number_tl: "199_4"
            truncation: "TCO"
        TL255:
            nx: 88838
            ny: 1
            oasis_grid_name: "128"
            res_number: 255
            res_number_tl: "255l_2"
            truncation: "TL"
        TCO319:
            nx: 421120
            ny: 1
            oasis_grid_name: 320
            res_number: 319
            res_number_tl: "319_4"
            truncation: "TCO"
        TCO399:
            nx: 654400
            ny: 1
            oasis_grid_name: 400
            res_number: 399
            res_number_tl: "399_4"
            truncation: "TCO"
        TCO639:
            nx: 1661440
            ny: 1
            oasis_grid_name: 640
            res_number: 639
            res_number_tl: "639_4"
            truncation: "TCO"
        TCO1279:
            nx: 6599680
            ny: 1
            oasis_grid_name: 128
            res_number: 1279
            res_number_tl: "1279_4"
            truncation: "TCO"
        TL511:
            nx: 348528
            ny: 1
            oasis_grid_name: "256"
            res_number: 511
            res_number_tl: "511l_2"
            truncation: "TL"
        TL799:
            nx: 843490
            ny: 1
            oasis_grid_name: "400"
            res_number: 799
            res_number_tl: "799l_2"
            truncation: "TL"
        TL1279:
            nx: 2140702
            ny: 1
            oasis_grid_name: "640"
            res_number: 799
            res_number_tl: "1279l_2"
            truncation: "TL"


computer:
    add_export_vars:
        myfortrancompiler: $FC
        #mygrid: TL159
        #mygrid: TL255
        mygrid: TCO319
        OASIS_ANCHOR: ../../../oasis
        NETCDF_C_DIR: $NETCDFROOT
        NETCDF_F_DIR: $NETCDFFROOT
        OASIS_DIR: ../../../oasis/arch_ecearth/
