# GET THIS INFORMATION DIRECTLY FROM ECHAM:

#repo_tag: ${echam.repo_tag}
model_dir: ${echam.model_dir}
resolution: ${echam.resolution}
scenario: ${echam.scenario}
lresume: ${echam.lresume}
time_step: ${echam.time_step}
parent_date: ${echam.parent_date}
prev_date: ${echam.prev_date}
ini_restart_dir: ${echam.parent_restart_dir}/../jsbach/
ini_parent_exp_id: ${echam.parent_expid}
#ini_parent_date: ${echam.ini_parent_date}
