# Setup up compile and runtime environment i.e. what needs
# to be changed w.r.t the default config/machines/<computer>.yaml

environment_changes:
    add_export_vars:
        DATA: "${general.work_dir}"
        GRIB_SAMPLES_PATH: '${model_dir}/build/share/eccodes/ifs_samples/grib1_mlgrib2'
        OIFS_LOGFILE: '${model_dir}/build/oifs_test_log.txt'
        LD_LIBRARY_PATH[(2)]: '${oifs.model_dir}/build/lib:$LD_LIBRARY_PATH'
        LD_LIBRARY_PATH[(3)]: '$HDF5ROOT/lib:$NETCDFROOT/lib:$NETCDFFROOT/lib:$LD_LIBRARY_PATH'
        LD_LIBRARY_PATH[(4)]: '${fesom.model_dir}/lib:$LD_LIBRARY_PATH'

        # Runoff mapper uses make not cmake, and so needs some vars.
        RNF_OASIS_BASE: '$(pwd)/oasis'
        RNF_OASIS_INCLUDE: '"-I$RNF_OASIS_BASE/build/lib/psmile -I$RNF_OASIS_BASE/build/lib/psmile/scrip -I$RNF_OASIS_BASE/build/lib/psmile/mct -I$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu"'
        RNF_OASIS_LIB: '"-L$RNF_OASIS_BASE/build/lib/psmile -L$RNF_OASIS_BASE/build/lib/psmile/scrip -L$RNF_OASIS_BASE/build/lib/psmile/mct -L$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"'
        # netcdf
        RNF_NETCDF_INCLUDE: '"-I$NETCDFROOT/include"'
        RNF_NETCDF_LIB: '"-L$NETCDFROOT/lib -lnetcdf"'
        RNF_NETCDFF_INCLUDE: '"-I$NETCDFFROOT/include"'
        RNF_NETCDFF_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
        RNF_MPI_LIB: '"$MPI_LIB"'

    choose_computer.name:
        levante:
            compiler_mpi: gnu11_ompi4
            iolibraries: system_gnu_libs
            add_add_export_vars:
                OIFS_DATA_DIR: "/p/project/chhb19/streffing1/input/oifs-48r1/"
        juwels:
            compiler_mpi: gnu2023_ompi2023
            iolibraries: system_libs

