components:
- xios-2.5.1
- rnfmap-v1.2
- oifs-48r1v2
- fesom-2.7.3
- oasis3mct-5.1
coupling_changes:
- sed -i 's/xios-2.5+/xios/g' oifs-48r1/bundle.yml
- sed -i 's/xios\/build_ecearth/xios/g' oifs-48r1/bundle.yml
- sed -i 's/oasis3-mct-5.2/oasis/g' oifs-48r1/bundle.yml
