name: CI-juwels-install-run-foci 
jobs:
  install_models:
    runs-on:
    - juwels
    strategy:
      fail-fast: false
      matrix:
        model:
        - foci-default 
        #- focioifs-2.0
    steps:
    - uses: actions/checkout@v2
    - name: Compile Model
      run: |
        module list
  run_models:        
    runs-on:
    - juwels
    needs: install_models
    strategy:
      fail-fast: false
      matrix:
        model:
        - foci-default 
    steps:
    - name: Run Test Simulation 
      run: |
        module list
on:
  pull_request:
    branches:
    - release
    - develop
    - '*prep-release*'
    - feature/CI-test
    #paths:
    #- configs/setups/foci.yaml
    #- configs/components/xios.yaml
    #- configs/components/echam.yaml
    #- configs/components/nemo.yaml
    #- configs/components/oasis3mct/oasis3mct.yaml
    #- configs/couplings/nemo-ORCA05_LIM2_KCM_AOW+echam-6.3.05p2-foci.yaml
  push:
    branches:
    - release
    - develop
    - '*prep-release*'
    - feature/CI-test
    #paths:
    #- configs/setups/foci.yaml
    #- configs/components/xios.yaml
    #- configs/components/echam.yaml
    #- configs/components/nemo.yaml
    #- configs/components/oasis3mct/oasis3mct.yaml
    #- configs/couplings/nemo-ORCA05_LIM2_KCM_AOW+echam-6.3.05p2-foci.yaml
