name: Tests for FESOM Standalone

on:
    push:
        paths:
            - '!docs/**'
            - '!README.md'
            - 'src/**'
            - 'tests/**'
            - 'configs/machines/ollie.yaml'
            - 'configs/components/fesom/*.yaml'
            - '.github/workflows/esm_tools_fesom-standalone.yml'

jobs:
    compile-ollie:
        name: Compile Test fesom-standalone (Ollie)
        # Pattern for uses: github-org/repo/some/path/in/repo@commit_or_branch
        # If @commit_or_branch is ommited, github actions will break!
        # For now, I tie it to release, but there might be better ways of doing
        # that, see for instance here: https://tinyurl.com/4x6h373j
        uses: "esm-tools/esm_tools/.github/workflows/esm_tools_actions_hpc_awi_ollie.yml@release"
        secrets:
          dkrz-token: ${{ secrets.GITLAB_DKRZ_TOKEN }}
          awi-token: ${{ secrets.GITLAB_AWI_TOKEN }}
        with:
          model_name: fesom
          # versions to test as a space seperated list
          model_version: "1.4-esm_interface 1.4 2.0-jio 2.0-o 2.0-paleodyn 2.0-r 2.0 2.1"
