name: Tests for PISM Standalone

on:
    push:
        paths:
            - '!docs/**'
            - '!README.md'
            - 'src/**'
            - 'tests/**'
            - 'configs/machines/ollie.yaml'
            - 'configs/components/pism/*.yaml'
            - '.github/workflows/esm_tools_pism-standalone.yml'

jobs:
    compile-ollie:
        name: Compile Test pism-standalone (Ollie)
        # Pattern for uses: github-org/repo/some/path/in/repo@commit_or_branch
        # If @commit_or_branch is ommited, github actions will break!
        # For now, I tie it to release, but there might be better ways of doing
        # that, see for instance here: https://tinyurl.com/4x6h373j
        uses: "esm-tools/esm_tools/.github/workflows/esm_tools_actions_hpc_awi_ollie.yml@release"
        secrets:
          dkrz-token: ${{ secrets.GITLAB_DKRZ_TOKEN }}
          awi-token: ${{ secrets.GITLAB_AWI_TOKEN }}
        with:
          model_name: pism
          # versions to test as a space seperated list
          model_version: "github1.1.4 github1.2 github1.2.1 index1.1"
