name: CI for VCS
on:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Update apt-get
              run: sudo apt-get update -y && sudo apt-get upgrade -y
            - name: Install Dependencies
              run: |
                  sudo apt-get install -y \
                      build-essential \
                      gfortran \
                      libnetcdf-dev \
                      libnetcdff-dev \
                      libhdf5-dev
            - name: Install up Cmake
              run: sudo apt-get install -y cmake
            - name: Install modulefiles
              run: |
                  sudo apt-get install -y environment-modules
                  source /etc/profile.d/modules.sh
            - name: Set up work folders
              run: |
                  sudo mkdir -p /work/esm-bot/my-project/model-codes
                  sudo mkdir -p /work/esm-bot/my-project/experiments
                  sudo mkdir -p /work/esm-bot/my-project/run-configs
                  sudo chown -R runner /work/esm-bot
            - name: Install esm-tools
              run: "export LC_ALL=\"en_US.UTF-8\"\nexport LANG=\"en_US.UTF-8\" \nPATH=${HOME}/.local/bin:${PATH}\n./install.sh\n"
            - name: Set up the dummy model
              run: |
                  cd /work/esm-bot/my-project/model-codes
                  PATH=${HOME}/.local/bin:${PATH}
                  whoami
                  ls -ratl .
                  esm_master install-dummy_model-1.0
            - name: Sanity check
              run: |
                  ls -l /work/esm-bot/my-project/model-codes/dummy_model-1.0/bin/HelloWorld
                  /work/esm-bot/my-project/model-codes/dummy_model-1.0/bin/HelloWorld

            - name: Copy test runscript
              run: |
                  cp runscripts/dummy-model/dummy-model.yaml /work/esm-bot/my-project/run-configs/

            - name: One small run
              run: |
                  cd /work/esm-bot/my-project/run-configs
                  export PATH=${HOME}/.local/bin:${PATH}
                  esm_runscripts dummy-model.yaml

            - name: Make model source change
              run: |
                  sed -i s/\!// /work/esm-bot/my-project/model-codes/dummy_model-1.0/src/hello.f90

            - name: Recompile
              run: |
                  cd /work/esm-bot/my-project/model-codes
                  PATH=${HOME}/.local/bin:${PATH}
                  whoami
                  ls -ratl .
                  esm_master recomp-dummy_model-1.0

            - name: One small run
              run: |
                  cd /work/esm-bot/my-project/run-configs
                  export PATH=${HOME}/.local/bin:${PATH}
                  esm_runscripts dummy-model.yaml

            # - name: Check differences
